/** @file
  Definition for Oem Services Kernel.

;******************************************************************************
;* Copyright (c) 2012, Insyde Software Corp. All Rights Reserved.
;*
;* You may not reproduce, distribute, publish, display, perform, modify, adapt,
;* transmit, broadcast, present, recite, release, license or otherwise exploit
;* any part of this publication in any form, by any means, without the prior
;* written permission of Insyde Software Corporation.
;*
;******************************************************************************
*/

#ifndef _OEM_SERVICES_KERNEL_SUPPORT_INC_H_
#define _OEM_SERVICES_KERNEL_SUPPORT_INC_H_

#include <Uefi.h>

//
// ARG_COUNT for PEI phase common OemServices
//
#define  COMMON_BOOT_MODE_CREATE_FV_ARG_COUNT             1
#define  COMMON_CHANGE_BOOT_MODE_ARG_COUNT                2
#define  COMMON_GET_SMART_BOOT_POLICY_ARG_COUNT           2
#define  COMMON_GET_PEI_CRISIS_PROTECT_TABLE_ARG_COUNT    3
#define  COMMON_SET_PLATFORM_HARDWARE_SWITCH_ARG_COUNT    1
#define  COMMON_SET_DIMM_SMBUS_ADDR_ARG_COUNT             1
#define  COMMON_MODIFY_CLOCKGEN_INFO_ARG_COUNT            5
#define  COMMON_AFTER_MODIFY_CLOCKGEN_ARG_COUNT           0
#define  COMMON_DETECT_RECOVERY_REQUEST_ARG_COUNT         1
#define  COMMON_SET_RECOVERY_REQUEST_ARG_COUNT            0
#define  COMMON_HOOK_WHEN_RECOVERY_FAIL_ARG_COUNT         0
#define  COMMON_INIT_PLATFORMSTAGE1_ARG_COUNT             0
#define  COMMON_MODIFY_SETUPVAR_PLATFORMSTAGE2_ARG_COUNT  2
#define  COMMON_INIT_PLATFORMSTAGE2_ARG_COUNT             2
#define  COMMON_IS_BOOT_WITH_NO_CHANGE_ARG_COUNT          1
#define  COMMON_INIT_MEMORY_DISCOVER_CALLBACK_ARG_COUNT   1
#define  COMMON_SIO_PEI_INIT_ARG_COUNT                    3
#define  COMMON_GET_VERB_TABLE_ARG_COUNT                  1

//
// ARG_COUNT for DXE phase common OemServices
//
#define  COMMON_DMI_SWITCH_TABLE_ARG_COUNT                     2
#define  COMMON_BOOTMANGER_KEY_TABLE_ARG_COUNT                 2
#define  COMMON_POST_KEY_TABLE_ARG_COUNT                       3
#define  COMMON_PCI_SKIP_TABLE_INDEX_ARG_COUNT                 2
#define  COMMON_LEGACY_BIOS_OEM_SLP_ARG_COUNT                  2
#define  COMMON_GET_MAX_CHECK_COUNT_ARG_COUNT                  1
#define  COMMON_ERROR_PASSWORD_CALL_BACK_ARG_COUNT             0
#define  COMMON_PASSWORD_ENTRY_CALL_BACK_ARG_COUNT             0
#define  COMMON_UPDATE_SCU_SYSTEM_INFO_ARG_COUNT               4
#define  COMMON_SCU_CALLBACK_FUNCTION_ARG_COUNT                9
#define  COMMON_CHECK_VGA_ORDER_ARG_COUNT                      4
#define  COMMON_DISPLAY_LOGO_ARG_COUNT                         1
#define  COMMON_CALCULATE_WRITE_CMOS_CHECKSUM_ARG_COUNT        0
#define  COMMON_CSM16_REFER_SWITCH_ARG_COUNT                   1
#define  COMMON_UPDATE_SLP20_PUBKEY_AND_SLP_MARKER_ARG_COUNT   4
#define  COMMON_UPDATE_OA30_MSDM_DATA_ARG_COUNT                2
#define  COMMON_FORM_LENGTH_UDPATE_ARG_COUNT                   5
#define  COMMON_GET_MULTI_SIO_RESOURCE_TABLE_ARG_COUNT         2
#define  COMMON_LOAD_DEFAULT_SETUP_MENU_ARG_COUNT              1
#define  COMMON_LOGO_RESOLUTION_ARG_COUNT                      1
#define  COMMON_IRQ_ROUTING_TABLE_ARG_COUNT                    1
#define  COMMON_OPTION_ROM_TABLE_ARG_COUNT                     2
#define  COMMON_UNSKIP_PCI_DEVICE_ARG_COUNT                    5
#define  COMMON_GET_HOTPLUG_BRIDGE_INFO_ARG_COUNT              1
#define  COMMON_UNLOAD_PCI_OPTION_ROM_ARG_COUNT                7
#define  COMMON_BOOT_DISPLAY_DEVICE_REPLACE_ARG_COUNT          1
#define  COMMON_PREPARE_INSTALL_MP_TABLE_ARG_COUNT             14
#define  COMMON_GET_SIO_RESOURCE_TABLE_ARG_COUNT               2
#define  COMMON_INSTALL_PCI_ROM_SWITCH_TEXT_MODE_ARG_COUNT     4
#define  COMMON_DISPLAY_SPI_NOT_SUPPORT_ARG_COUNT              0
#define  COMMON_UPDATE_BBS_TABLE_ARG_COUNT                     2
#define  COMMON_GET_SSID_SVID_INFO_CALLBACK_ARG_COUNT          7
#define  COMMON_VARIABLE_RESERVED_TABLE_ARG_COUNT              2

//
// ARG_COUNT for SMM phase common OemServices
//
#define  COMMON_PNP_UPDATE_STRING_TABLE_ARG_COUNT             2
#define  COMMON_PNP_GPNV_HANDLE_TABLE_ARG_COUNT               2
#define  COMMON_SMM_S1_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S3_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S4_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S5_CALLBACK_ARG_COUNT                     0
#define  COMMON_SMM_S5_AC_LOSS_CALLBACK_ARG_COUNT             0
#define  COMMON_SMM_ENABLE_ACPI_CALLBACK_ARG_COUNT            0
#define  COMMON_SMM_DISABLE_ACPI_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_RESTORE_ACPI_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_POWER_BUTTON_CALLBACK_ARG_COUNT           0
#define  COMMON_SMM_ASPM_OVERRIDE_CALLBACK_ARG_COUNT          1
#define  COMMON_SMM_OS_RESET_CALLBACK_ARG_COUNT               0

typedef enum {
  COMMON_BOOT_MODE_CREATE_FV,
  COMMON_CHANGE_BOOT_MODE,
  COMMON_GET_SMART_BOOT_POLICY,
  COMMON_GET_PEI_CRISIS_PROTECT_TABLE,
  COMMON_SET_PLATFORM_HARDWARE_SWITCH,
  COMMON_SET_DIMM_SMBUS_ADDR,
  COMMON_MODIFY_CLOCKGEN_INFO,
  COMMON_AFTER_MODIFY_CLOCKGEN,
  COMMON_DETECT_RECOVERY_REQUEST,
  COMMON_SET_RECOVERY_REQUEST,
  COMMON_HOOK_WHEN_RECOVERY_FAIL,
  COMMON_INIT_PLATFORMSTAGE1,
  COMMON_MODIFY_SETUPVAR_PLATFORMSTAGE2,
  COMMON_INIT_PLATFORMSTAGE2,
  COMMON_IS_BOOT_WITH_NO_CHANGE,
  COMMON_INIT_MEMORY_DISCOVER_CALLBACK,
  COMMON_SIO_PEI_INIT,
  COMMON_GET_VERB_TABLE,
  PEI_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_PEI_COMMON_SUPPORT;

typedef enum {
  COMMON_DMI_SWITCH_TABLE,       //0
  COMMON_BOOTMANGER_KEY_TABLE,   //1
  COMMON_POST_KEY_TABLE,         //2
  COMMON_PCI_SKIP_TABLE_INDEX,   //3
  COMMON_LEGACY_BIOS_OEM_SLP,    //4
  COMMON_GET_MAX_CHECK_COUNT,    //5
  COMMON_ERROR_PASSWORD_CALL_BACK, //6
  COMMON_PASSWORD_ENTRY_CALL_BACK, //7
  COMMON_UPDATE_SCU_SYSTEM_INFO,   //8
  COMMON_SCU_CALLBACK_FUNCTION,    //9
  COMMON_CHECK_VGA_ORDER,          //10
  COMMON_DISPLAY_LOGO,             //11
  COMMON_CALCULATE_WRITE_CMOS_CHECKSUM, //12
  COMMON_CSM16_REFER_SWITCH,            //13
  COMMON_UPDATE_SLP20_PUBKEY_AND_SLP_MARKER, //14
  COMMON_UPDATE_MSDM_DATA,                   //15
  COMMON_FORM_LENGTH_UDPATE,                 //16
  COMMON_GET_MULTI_SIO_RESOURCE_TABLE,       //17
  COMMON_LOAD_DEFAULT_SETUP_MENU,            //18
  COMMON_LOGO_RESOLUTION,                    //19
  COMMON_IRQ_ROUTING_TABLE,                  //20
  COMMON_OPTION_ROM_TABLE,                   //21
  COMMON_UNSKIP_PCI_DEVICE,                  //22
  COMMON_GET_HOTPLUG_BRIDGE_INFO,            //23
  COMMON_UNLOAD_PCI_OPTION_ROM,              //24
  COMMON_BOOT_DISPLAY_DEVICE_REPLACE,        //25
  COMMON_PREPARE_INSTALL_MP_TABLE,           //26
  COMMON_GET_SIO_RESOURCE_TABLE,             //27
  COMMON_INSTALL_PCI_ROM_SWITCH_TEXT_MODE,   //28
  COMMON_DISPLAY_SPI_NOT_SUPPORT,
  COMMON_UPDATE_BBS_TABLE,
  COMMON_GET_SSID_SVID_INFO_CALLBACK,
  COMMON_PNP_DXE_UPDATE_STRING_TABLE,
  COMMON_PNP_DXE_GPNV_HANDLE_TABLE,
  COMMON_VARIABLE_RESERVED_TABLE,
  RUNTIME_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_RUNTIME_COMMON_SUPPORT;

typedef enum {
  COMMON_PNP_UPDATE_STRING_TABLE,
  COMMON_PNP_GPNV_HANDLE_TABLE,
  COMMON_SMM_S1_CALLBACK,
  COMMON_SMM_S3_CALLBACK,
  COMMON_SMM_S4_CALLBACK,
  COMMON_SMM_S5_CALLBACK,
  COMMON_SMM_S5_AC_LOSS_CALLBACK,
  COMMON_SMM_ENABLE_ACPI_CALLBACK,
  COMMON_SMM_DISABLE_ACPI_CALLBACK,
  COMMON_SMM_RESTORE_ACPI_CALLBACK,
  COMMON_SMM_POWER_BUTTON_CALLBACK,
  COMMON_SMM_ASPM_OVERRIDE_CALLBACK,
  COMMON_SMM_OS_RESET_CALLBACK,
  COMMON_VARIABLE_PRESERVED_TABLE,
  SMM_MAX_NUM_COMMON_SUPPORT
} OEM_SERVICES_SMM_COMMON_SUPPORT;
#endif
