/** @file
  File name:    MmrcProjectDataGenerated.h
  Input File:   BXTP_SOC.xlsx

  THIS FILE IS AUTO-GENERATED BY THE MMRC TOOL. DO NOT CHANGE THIS CODE.

  If edits are needed in this file, they must be done via the MMRC tool.

  If there is additional project-specific data required by the MMRC, it
  can be placed in MmrcProjectData.h, which is used for non-tool-generated
  data

  This file contains data structures for a particular piece of silicon.
  These structures are fed to MmrcLibraries.c, which use them to initialize
  memory.

 @copyright
  INTEL CONFIDENTIAL
  Copyright 2005 - 2016 Intel Corporation.

  The source code contained or described herein and all documents related to the
  source code ("Material") are owned by Intel Corporation or its suppliers or
  licensors. Title to the Material remains with Intel Corporation or its suppliers
  and licensors. The Material may contain trade secrets and proprietary and
  confidential information of Intel Corporation and its suppliers and licensors,
  and is protected by worldwide copyright and trade secret laws and treaty
  provisions. No part of the Material may be used, copied, reproduced, modified,
  published, uploaded, posted, transmitted, distributed, or disclosed in any way
  without Intel's prior express written permission.

  No license under any patent, copyright, trade secret or other intellectual
  property right is granted to or conferred upon you by disclosure or delivery
  of the Materials, either expressly, by implication, inducement, estoppel or
  otherwise. Any license under such intellectual property rights must be
  express and approved by Intel in writing.

  Unless otherwise agreed by Intel in writing, you may not remove or alter
  this notice or any other notice embedded in Materials by Intel or
  Intel's suppliers or licensors in any way.

  This file contains an 'Intel Peripheral Driver' and is uniquely identified as
  "Intel Reference Module" and is licensed for Intel CPUs and chipsets under
  the terms of your license agreement with Intel or your vendor. This file may
  be modified by the user, subject to additional terms of the license agreement.

  @par Specification
**/
#ifndef _MMRCPROJECTDATAGENERATED_H_
#define _MMRCPROJECTDATAGENERATED_H_

#include "MmrcData.h"

extern char *CapsuleStrings[];
//
// Invalid value for a Blueprint define
//
#define INVALID_BLUEPRINT_DEFINE_VALUE                     0xDEADBEEF
//
// Blueprint project defines for BLUEPRINT_LPDDR34
//
#define test_BLUEPRINT_LPDDR34                             1
//
// Blueprint project defines for BLUEPRINT_DDR3
//
#define test_BLUEPRINT_DDR3                                2

#if MAX_BLUEPRINTS > 1
  extern UINT32 test_GENERATED[MAX_BLUEPRINTS];
  #define test test_GENERATED[MrcData->CurrentBlueprint]
#else
  extern UINT32 test_GENERATED;
  #define test test_GENERATED
#endif

#endif // _MMRCPROJECTDATAGENERATED_H_
