## @file
#  Project Makefile
#
#******************************************************************************
#* Copyright (c) 2012 - 2015, Insyde Software Corp. All Rights Reserved.
#*
#* You may not reproduce, distribute, publish, display, perform, modify, adapt,
#* transmit, broadcast, present, recite, release, license or otherwise exploit
#* any part of this publication in any form, by any means, without the prior
#* written permission of Insyde Software Corporation.
#*
#******************************************************************************

#
# Build mode customization
# -q: Quiet mode   - disable all messages except fatal errors, module based messages.
#                    this is default build mode if BUILD_MODE is not specified
# -s: Silent mode  - file based messages
# -v: Verbose mode - Turn on verbose output with informational messages printed
#
#BUILD_MODE     = -s

#
# Build report customization
# Below is the default build report setting if BUILD_REPORT is not specified
#BUILD_REPORT = -Y PCD -Y DEPEX -Y LIBRARY -y $(WORKSPACE)/Build/$(PROJECT_PKG)/BuildReport.txt

#
# Add additional project build options here
#
#PROJECT_BUILD_OPTIONS =

uefi32:
	@echo "Please key-in \"nmake nt32\" to build 32-bits emulator, not uefi32"
	@exit 
  
uefi64:
	@echo "Please key-in \"nmake nt64\" to build 64-bits emulator, not uefi64"
	@exit

!include $(WORKSPACE)\BaseTools\Conf\Makefile
