/** @file
  PCI device Lookup Table

;******************************************************************************
;* Copyright (c) 2014, Insyde Software Corp. All Rights Reserved.
;*
;* You may not reproduce, distribute, publish, display, perform, modify, adapt,
;* transmit, broadcast, present, recite, release, license or otherwise exploit
;* any part of this publication in any form, by any means, without the prior
;* written permission of Insyde Software Corporation.
;*
;******************************************************************************
*/

#include "PciDevLookupTable.h"

typedef struct{
  UINT16  VendorId;
  CHAR16  *ShortName;
  CHAR16  *LongName;
} PCI_VENDOR_TABLE;

PCI_VENDOR_TABLE mPciVenTable[] = {
  { 0x0033,   L"Parad." ,   L"Paradyne Corp."},
  { 0x003D,   L"Master" ,   L"Master"},
  { 0x0070,   L"Haupp." ,   L"Hauppauge Computer Works Inc."},
  { 0x0100,   L"nciph." ,   L"USBPDO-8"},
  { 0x0123,   L"Gener." ,   L"General Dynamics"},
  { 0x0315,   L"SK    " ,   L"SK - Electronics Co., Ltd."},
  { 0x0402,   L"Acer  " ,   L"Acer aspire one"},
  { 0x046D,   L"Logit." ,   L"Logitech Inc."},
  { 0x0483,   L"UPEK  " ,   L"UPEK"},
  { 0x04A9,   L"Canon " ,   L"Canon"},
  { 0x04B3,   L"IBM   " ,   L"IBM"},
  { 0x04D9,   L"Filco " ,   L"Filco"},
  { 0x04F2,   L"Chico." ,   L"Chicony Electronics Co. "},
  { 0x051D,   L"INT33." ,   L"APC"},
  { 0x0529,   L"Aladd." ,   L"Aladdin E-Token"},
  { 0x0553,   L"Aiptek" ,   L"Aiptek USA"},
  { 0x058f,   L"Alcor " ,   L"Alcor Micro Corp."},
  { 0x0590,   L"Omron " ,   L"Omron Corp"},
  { 0x05ac,   L"Apple " ,   L"Apple, Inc."},
  { 0x05E1,   L"D-MAX " ,   L"D-MAX"},
  { 0x064e,   L"Suyin " ,   L"SUYIN Corporation"},
  { 0x067B,   L"Proli." ,   L"Prolific Technology Inc."},
  { 0x06FE,   L"Acres." ,   L"Acresso Software Inc."},
  { 0x0711,   L"SIIG,." ,   L"SIIG, Inc."},
  { 0x093a,   L"Genius" ,   L"KYE Systems Corp."},
  { 0x096E,   L"USB R." ,   L"USB Rockey dongle from Feitain "},
  { 0x0A5C,   L"BCM   " ,   L"Broadcom Corporation"},
  { 0x0A89,   L"BREA  " ,   L"BREA Technologies Inc."},
  { 0x0A92,   L"Egosys" ,   L"Egosys, Inc."},
  { 0x0AC8,   L"ASUS  " ,   L"ASUS "},
  { 0x0b05,   L"Toshi." ,   L"Toshiba Bluetooth RFBUS, RFCOM, RFHID"},
  { 0x0c45,   L"Micro." ,   L"Microdia Ltd."},
  { 0x0cf3,   L"TP-Li." ,   L"TP-Link"},
  { 0x0D2E,   L"Feedb." ,   L"Feedback Instruments Ltd."},
  { 0x0D8C,   L"C-Med." ,   L"C-Media Electronics, Inc."},
  { 0x0DF6,   L"Sitec." ,   L"Sitecom"},
  { 0x0E11,   L"Compaq" ,   L"dell Computer Corp."},
  { 0x0E8D,   L"Media." ,   L"MediaTek Inc."},
  { 0x1000,   L"LSI   " ,   L"LSI Logic"},
  { 0x1001,   L"KOLTER" ,   L"Kolter Electronic - Germany"},
  { 0x1002,   L"ATI   " ,   L"ATI Technologies Inc. / Advanced Micro Devices, Inc."},
  { 0x1003,   L"ULSI  " ,   L"ULSI"},
  { 0x1004,   L"VLSI  " ,   L"VLSI Technology"},
  { 0x1006,   L"Reply " ,   L"Reply Group"},
  { 0x1007,   L"NetFr." ,   L"Netframe Systems Inc."},
  { 0x1008,   L"Epson " ,   L"Epson"},
  { 0x100A,   L"Phoen." ,   L"A?as Ltd. de Phoenix del A? de TecnologA?"},
  { 0x100B,   L"NSC   " ,   L"National Semiconductors"},
  { 0x100C,   L"Tseng " ,   L"Tseng Labs"},
  { 0x100D,   L"AST   " ,   L"AST Research"},
  { 0x100E,   L"Weitek" ,   L"Weitek"},
  { 0x1010,   L"VLogic" ,   L"Video Logic Ltd."},
  { 0x1011,   L"DEC   " ,   L"Digital Equipment Corporation"},
  { 0x1012,   L"Micro." ,   L"Micronics Computers Inc."},
  { 0x1013,   L"Cirrus" ,   L"Cirrus Logic"},
  { 0x1014,   L"IBM   " ,   L"International Business Machines Corp."},
  { 0x1016,   L"Fujit." ,   L"Fujitsu ICL Computers"},
  { 0x1017,   L"Spea  " ,   L"Spea Software AG"},
  { 0x1018,   L"Unisys" ,   L"Unisys Systems"},
  { 0x1019,   L"ECS   " ,   L"Elitegroup Computer System"},
  { 0x101A,   L"NCR   " ,   L"NCR Corporation"},
  { 0x101B,   L"Vites." ,   L"Vitesse Semiconductor"},
  { 0x101E,   L"AMI   " ,   L"American Megatrends Inc."},
  { 0x101F,   L"Pictu." ,   L"PictureTel Corp."},
  { 0x1020,   L"Hitac." ,   L"Hitachi Computer Electronics"},
  { 0x1021,   L"OKI   " ,   L"Oki Electric Industry"},
  { 0x1022,   L"AMD   " ,   L"Advanced Micro Devices"},
  { 0x1023,   L"machdo" ,   L"TRIDENT MICRO"},
  { 0x1025,   L"Acer  " ,   L"Acer Incorporated"},
  { 0x1028,   L"Dell  " ,   L"Dell Computer Corporation"},
  { 0x102A,   L"LSI   " ,   L"LSI Logic Headland Division"},
  { 0x102B,   L"Matrox" ,   L"Matrox Electronic Systems Ltd."},
  { 0x102C,   L"C&T   " ,   L"Asiliant (Chips And Technologies)"},
  { 0x102D,   L"Wyse  " ,   L"Wyse Technologies"},
  { 0x102E,   L"Olive." ,   L"Olivetti Advanced Technology"},
  { 0x102F,   L"U305-." ,   L"Toshiba America"},
  { 0x1030,   L"TMC   " ,   L"TMC Research"},
  { 0x1031,   L"miro ." ,   L"miro Computer Products AG"},
  { 0x1033,   L"NEC   " ,   L"NEC Electronics"},
  { 0x1034,   L"Burndy" ,   L"Burndy Corporation"},
  { 0x1036,   L"FDoma." ,   L"Future Domain"},
  { 0x1037,   L"Hitac." ,   L"Hitachi Micro Systems Inc"},
  { 0x1038,   L"AMP   " ,   L"AMP Incorporated"},
  { 0x1039,   L"Silic." ,   L"SIS"},
  { 0x103A,   L"Seiko " ,   L"Seiko Epson Corporation"},
  { 0x103B,   L"Tatung" ,   L"Tatung Corp. Of America"},
  { 0x103C,   L"tx1ooo" ,   L"Hewlett-Packard - HP dc7800"},
  { 0x103E,   L"Solli." ,   L"Solliday Engineering"},
  { 0x103F,   L"Logic." ,   L"Logic Modeling"},
  { 0x1041,   L"Compu." ,   L"Computrend"},
  { 0x1043,   L"Asust." ,   L"Asustek Computer Inc."},
  { 0x1044,   L"DPT   " ,   L"Distributed Processing Tech"},
  { 0x1045,   L"OPTi  " ,   L"OPTi Inc."},
  { 0x1046,   L"IPC   " ,   L"IPC Corporation LTD"},
  { 0x1047,   L"Genoa " ,   L"Genoa Systems Corp."},
  { 0x1048,   L"ELSA  " ,   L"ELSA GmbH"},
  { 0x1049,   L"Fount." ,   L"Fountain Technology"},
  { 0x104A,   L"STM   " ,   L"STMicroelectronics"},
  { 0x104B,   L"Mylexv" ,   L"Mylex / Buslogic"},
  { 0x104C,   L"TSIK  " ,   L"Texas Instruments"},
  { 0x104D,   L"Sony  " ,   L"Sony Corporation"},
  { 0x104E,   L"Oak   " ,   L"Oak Technology"},
  { 0x104F,   L"Co-Ti." ,   L"Co-Time Computer Ltd."},
  { 0x1050,   L"Winbo." ,   L"Winbond Electronics Corp."},
  { 0x1051,   L"Anigma" ,   L"Anigma Corp."},
  { 0x1053,   L"Young " ,   L"Young Micro Systems"},
  { 0x1054,   L"Hitac." ,   L"Hitachi Ltd"},
  { 0x1055,   L"SMSC  " ,   L"Standard Microsystems Corp."},
  { 0x1056,   L"ICL   " ,   L"ICL"},
  { 0x1057,   L"Motor." ,   L"Motorola"},
  { 0x1058,   L"E&TR  " ,   L"Electronics & Telecommunication Res"},
  { 0x1059,   L"Kontr." ,   L"Kontron Canada"},
  { 0x105A,   L"Promi." ,   L"Promise Technology"},
  { 0x105B,   L"Foxco." ,   L"Foxconn International Inc."},
  { 0x105C,   L"Wipro " ,   L"Wipro Infotech Limited"},
  { 0x105D,   L"Numbe." ,   L"Number Nine Visual Technology"},
  { 0x105E,   L"Vtech " ,   L"Vtech Engineering Canada Ltd."},
  { 0x105F,   L"Infot." ,   L"Infotronic America Inc."},
  { 0x1060,   L"UMC   " ,   L"United Microelectronics"},
  { 0x1061,   L"8x8   " ,   L"8x8 Inc."},
  { 0x1062,   L"Maspar" ,   L"Maspar Computer Corp."},
  { 0x1063,   L"OOA   " ,   L"Ocean Office Automation"},
  { 0x1064,   L"Alcat." ,   L"Alcatel Cit"},
  { 0x1065,   L"TM    " ,   L"Texas Microsystems"},
  { 0x1066,   L"Picop." ,   L"Picopower Technology"},
  { 0x1067,   L"Mitsu." ,   L"Mitsubishi Electronics"},
  { 0x1068,   L"Div.  " ,   L"Diversified Technology"},
  { 0x106A,   L"Aten  " ,   L"Aten Research Inc."},
  { 0x106B,   L"Apple " ,   L"Apple Inc."},
  { 0x106C,   L"Hyund." ,   L"Hyundai Electronics America"},
  { 0x106D,   L"Seque." ,   L"Sequent Computer Systems"},
  { 0x106E,   L"DFI   " ,   L"DFI Inc."},
  { 0x106F,   L"CityG." ,   L"City Gate Development LTD"},
  { 0x1070,   L"Daewoo" ,   L"Daewoo Telecom Ltd."},
  { 0x1071,   L"Mitac " ,   L"Mitac"},
  { 0x1072,   L"GIT   " ,   L"GIT Co. Ltd."},
  { 0x1073,   L"Yamaha" ,   L"Yamaha Corporation"},
  { 0x1074,   L"Nexgen" ,   L"Nexgen Microsystems"},
  { 0x1075,   L"AIR   " ,   L"Advanced Integration Research"},
  { 0x1077,   L"QLogic" ,   L"QLogic Corporation"},
  { 0x1078,   L"Cyrix " ,   L"Cyrix Corporation"},
  { 0x1079,   L"I-Bus " ,   L"I-Bus"},
  { 0x107A,   L"Netwo." ,   L"Networth controls"},
  { 0x107B,   L"Gatew." ,   L"Gateway 2000"},
  { 0x107C,   L"Golds." ,   L"Goldstar Co. Ltd."},
  { 0x107D,   L"Leadt." ,   L"Leadtek Research"},
  { 0x107E,   L"Inter." ,   L"Testernec"},
  { 0x107F,   L"DTC   " ,   L"Data Technology Corporation"},
  { 0x1080,   L"Cypre." ,   L"Cypress Semiconductor"},
  { 0x1081,   L"Radiu." ,   L"Radius Inc."},
  { 0x1082,   L"EFA   " ,   L"EFA Corporation Of America"},
  { 0x1083,   L"Forex " ,   L"Forex Computer Corporation"},
  { 0x1084,   L"Parad." ,   L"Parador"},
  { 0x1085,   L"Tulip " ,   L"Tulip Computers Int'l BV"},
  { 0x1086,   L"J. Bo." ,   L"J. Bond Computer Systems"},
  { 0x1087,   L"Cache " ,   L"Cache Computer"},
  { 0x1088,   L"MS So." ,   L"Microcomputer Systems (M) Son"},
  { 0x1089,   L"DG    " ,   L"Data General Corporation"},
  { 0x108A,   L"Bit3  " ,   L"SBS  Operations"},
  { 0x108C,   L"Oakle." ,   L"Oakleigh Systems Inc."},
  { 0x108D,   L"Olicom" ,   L"Olicom"},
  { 0x108E,   L"Sun   " ,   L"Sun Microsystems"},
  { 0x108F,   L"Syste." ,   L"Systemsoft Corporation"},
  { 0x1090,   L"Encore" ,   L"Encore Computer Corporation"},
  { 0x1091,   L"Inter." ,   L"Intergraph Corporation"},
  { 0x1092,   L"Diamo." ,   L"Diamond Computer Systems"},
  { 0x1093,   L"Nat. ." ,   L"National Instruments"},
  { 0x1094,   L"Apost." ,   L"Apostolos"},
  { 0x1095,   L"Silic." ,   L"Silicon Image, Inc."},
  { 0x1096,   L"Alacr." ,   L"Alacron"},
  { 0x1097,   L"Appian" ,   L"Appian Graphics"},
  { 0x1098,   L"Quant." ,   L"Quantum Designs Ltd."},
  { 0x1099,   L"Samsu." ,   L"Samsung Electronics Co. Ltd."},
  { 0x109A,   L"Packa." ,   L"Packard Bell"},
  { 0x109B,   L"Gemli." ,   L"Gemlight Computer Ltd."},
  { 0x109C,   L"Megac." ,   L"Megachips Corporation"},
  { 0x109D,   L"Zida  " ,   L"Zida Technologies Ltd."},
  { 0x109E,   L"Brook." ,   L"Brooktree Corporation"},
  { 0x109F,   L"Trigem" ,   L"Trigem Computer Inc."},
  { 0x10A0,   L"Meide." ,   L"Meidensha Corporation"},
  { 0x10A1,   L"Juko  " ,   L"Juko Electronics Inc. Ltd."},
  { 0x10A2,   L"Quant." ,   L"Quantum Corporation"},
  { 0x10A3,   L"Everex" ,   L"Everex Systems Inc."},
  { 0x10A4,   L"Globe " ,   L"Globe Manufacturing Sales"},
  { 0x10A5,   L"Racal " ,   L"Racal Interlan"},
  { 0x10A8,   L"Sierra" ,   L"Sierra Semiconductor"},
  { 0x10A9,   L"SG    " ,   L"Silicon Graphics"},
  { 0x10AB,   L"Digic." ,   L"Digicom"},
  { 0x10AC,   L"Honey." ,   L"Honeywell IASD"},
  { 0x10AD,   L"Winbo." ,   L"Winbond Systems Labs"},
  { 0x10AE,   L"Corne." ,   L"Cornerstone Technology"},
  { 0x10AF,   L"MCS   " ,   L"Micro Computer Systems Inc."},
  { 0x10B0,   L"Gainw." ,   L"Gainward GmbH "},
  { 0x10B1,   L"Cable." ,   L"Cabletron Systems Inc."},
  { 0x10B2,   L"Rayth." ,   L"Raytheon Company"},
  { 0x10B3,   L"Datab." ,   L"Databook Inc."},
  { 0x10B4,   L"STB   " ,   L"STB Systems"},
  { 0x10B5,   L"PLX   " ,   L"PLX Technology Inc."},
  { 0x10B6,   L"Madge " ,   L"Madge Networks"},
  { 0x10B7,   L"3Com  " ,   L"3Com Corporation"},
  { 0x10B8,   L"SMC   " ,   L"Standard Microsystems Corporation"},
  { 0x10B9,   L"Ali   " ,   L"Ali Corporation"},
  { 0x10BA,   L"Mitsu." ,   L"Mitsubishi Electronics Corp."},
  { 0x10BB,   L"Dapha " ,   L"Dapha Electronics Corporation"},
  { 0x10BC,   L"ALR   " ,   L"Advanced Logic Research Inc."},
  { 0x10BD,   L"Surec." ,   L"Surecom Technology"},
  { 0x10BE,   L"Tseng " ,   L"Tsenglabs International Corp."},
  { 0x10BF,   L"MOST  " ,   L"MOST Corp."},
  { 0x10C0,   L"Boca  " ,   L"Boca Research Inc."},
  { 0x10C1,   L"ICM   " ,   L"ICM Corp. Ltd."},
  { 0x10C2,   L"Auspex" ,   L"Auspex Systems Inc."},
  { 0x10C3,   L"Samsu." ,   L"Samsung Semiconductors"},
  { 0x10C4,   L"wim   " ,   L"Award Software Int'l Inc."},
  { 0x10C5,   L"Xerox " ,   L"Xerox Corporation"},
  { 0x10C6,   L"Rambus" ,   L"Rambus Inc."},
  { 0x10C8,   L"Neoma." ,   L"Neomagic Corporation"},
  { 0x10C9,   L"Datae." ,   L"Dataexpert Corporation"},
  { 0x10CA,   L"Fujit." ,   L"Fujitsu Siemens"},
  { 0x10CB,   L"Omron " ,   L"Omron Corporation"},
  { 0x10CD,   L"Advan." ,   L"Advanced System Products"},
  { 0x10CF,   L"Fujit." ,   L"Fujitsu Ltd."},
  { 0x10D1,   L"Futur." ,   L"Future+ Systems"},
  { 0x10D2,   L"Molex " ,   L"Molex Incorporated"},
  { 0x10D3,   L"Jabil " ,   L"Jabil Circuit Inc."},
  { 0x10D4,   L"Hualon" ,   L"Hualon Microelectronics"},
  { 0x10D5,   L"Autol." ,   L"Autologic Inc."},
  { 0x10D6,   L"Wilso." ,   L"Wilson .co .ltd"},
  { 0x10D7,   L"BCM   " ,   L"BCM Advanced Research"},
  { 0x10D8,   L"APL   " ,   L"Advanced Peripherals Labs"},
  { 0x10D9,   L"Macro." ,   L"Macronix International Co. Ltd."},
  { 0x10DB,   L"Rohm  " ,   L"Rohm Research"},
  { 0x10DC,   L"CERN  " ,   L"CERN-European Lab. for Particle Physics"},
  { 0x10DD,   L"E&S   " ,   L"Evans & Sutherland"},
  { 0x10DE,   L"NVIDIA" ,   L"NVIDIA Corporation"},
  { 0x10DF,   L"Emulex" ,   L"Emulex Corporation"},
  { 0x10E1,   L"Tekram" ,   L"Tekram Technology Corp. Ltd."},
  { 0x10E2,   L"Aptix " ,   L"Aptix Corporation"},
  { 0x10E3,   L"Tundra" ,   L"Tundra Semiconductor Corp."},
  { 0x10E4,   L"Tandem" ,   L"Tandem Computers"},
  { 0x10E5,   L"MIC   " ,   L"Micro Industries Corporation"},
  { 0x10E6,   L"Gainb." ,   L"Gainbery Computer Products Inc."},
  { 0x10E7,   L"Vadem " ,   L"Vadem"},
  { 0x10E8,   L"AMCC  " ,   L"Applied Micro Circuits Corp."},
  { 0x10E9,   L"Alps  " ,   L"Alps Electronic Corp. Ltd."},
  { 0x10EA,   L"Tvia  " ,   L"Tvia, Inc."},
  { 0x10EB,   L"Artist" ,   L"Artist Graphics"},
  { 0x10EC,   L"Realt." ,   L"Realtek Semiconductor Corp."},
  { 0x10ED,   L"Ascii " ,   L"Ascii Corporation"},
  { 0x10EE,   L"Xilinx" ,   L"Xilinx Corporation"},
  { 0x10EF,   L"Racore" ,   L"Racore Computer Products"},
  { 0x10F0,   L"Real-." ,   L"Curtiss-Wright Controls Embedded Computing"},
  { 0x10F1,   L"Tyan  " ,   L"Tyan Computer"},
  { 0x10F2,   L"Achme " ,   L"Achme Computer Inc. - GONE !!!!"},
  { 0x10F3,   L"Alaris" ,   L"Alaris Inc."},
  { 0x10F4,   L"S-Mos " ,   L"S-Mos Systems"},
  { 0x10F5,   L"NKK   " ,   L"NKK Corporation"},
  { 0x10F6,   L"CES   " ,   L"Creative Electronic Systems SA"},
  { 0x10F7,   L"Matsu." ,   L"Matsushita Electric Industrial Corp."},
  { 0x10F8,   L"Altos " ,   L"Altos India Ltd."},
  { 0x10F9,   L"PC-Di." ,   L"PC Direct"},
  { 0x10FA,   L"Truev." ,   L"Truevision"},
  { 0x10FB,   L"Thesys" ,   L"Thesys Microelectronic's"},
  { 0x10FC,   L"I-O   " ,   L"I-O Data Device Inc."},
  { 0x10FD,   L"Soyo  " ,   L"Soyo Technology Corp. Ltd."},
  { 0x10FE,   L"Fast  " ,   L"Fast Electronic GmbH"},
  { 0x10FF,   L"Ncube " ,   L"Ncube"},
  { 0x1100,   L"Jazz  " ,   L"Jazz Multimedia"},
  { 0x1101,   L"Initio" ,   L"Initio Corporation"},
  { 0x1102,   L"Creat." ,   L"Creative Technology LTD."},
  { 0x1103,   L"HighP." ,   L" HighPoint Technologies, Inc."},
  { 0x1104,   L"Raste." ,   L"Rasterops"},
  { 0x1105,   L"Sigma " ,   L"Sigma Designs Inc."},
  { 0x1106,   L"VIA   " ,   L"VIA Technologies, Inc."},
  { 0x1107,   L"Strat." ,   L"Stratus Computer"},
  { 0x1108,   L"Prote." ,   L"Proteon Inc."},
  { 0x1109,   L"Cogent" ,   L"Adaptec/Cogent Data Technologies"},
  { 0x110A,   L"Sieme." ,   L"Siemens Nixdorf AG"},
  { 0x110B,   L"Chrom." ,   L"Chromatic Research Inc"},
  { 0x110C,   L"Mini-." ,   L"Mini-Max Technology Inc."},
  { 0x110D,   L"ZNYX  " ,   L"ZNYX Corporation"},
  { 0x110E,   L"CPU T." ,   L"CPU Technology"},
  { 0x110F,   L"Ross  " ,   L"Ross Technology"},
  { 0x1112,   L"Osicom" ,   L"Osicom Technologies Inc."},
  { 0x1113,   L"Accton" ,   L"Accton Technology Corporation"},
  { 0x1114,   L"Atmel " ,   L"Atmel Corp."},
  { 0x1116,   L"Data ." ,   L"Data Translation, Inc."},
  { 0x1117,   L"Datac." ,   L"Datacube Inc."},
  { 0x1118,   L"Berg  " ,   L"Berg Electronics"},
  { 0x1119,   L"Vortex" ,   L"ICP vortex Computersysteme GmbH"},
  { 0x111A,   L"Eff. ." ,   L"Efficent Networks"},
  { 0x111C,   L"Trico." ,   L"Tricord Systems Inc."},
  { 0x111D,   L"IDT   " ,   L"Integrated Device Technology Inc."},
  { 0x111F,   L"PDI   " ,   L"Precision Digital Images"},
  { 0x1120,   L"EMC   " ,   L"EMC Corp."},
  { 0x1121,   L"Zilog " ,   L"Zilog"},
  { 0x1123,   L"EDI   " ,   L"Excellent Design Inc."},
  { 0x1124,   L"Leutr." ,   L"Leutron Vision AG"},
  { 0x1125,   L"Euroc." ,   L"Eurocore/Vigra"},
  { 0x1127,   L"FORE ." ,   L"FORE Systems"},
  { 0x1129,   L"Firmw." ,   L"Firmworks"},
  { 0x112A,   L"Hermes" ,   L"Hermes Electronics Co. Ltd."},
  { 0x112C,   L"Zenith" ,   L"Zenith Data Systems"},
  { 0x112D,   L"Ravic." ,   L"Ravicad"},
  { 0x112E,   L"Infom." ,   L"Infomedia"},
  { 0x1130,   L"Compu." ,   L"Computervision"},
  { 0x1131,   L"NXP   " ,   L"NXP Semiconductors N.V."},
  { 0x1132,   L"Mitel " ,   L"Mitel Corp."},
  { 0x1133,   L"EIC   " ,   L"Eicon Networks Corporation"},
  { 0x1134,   L"MCS   " ,   L"Mercury Computer Systems Inc."},
  { 0x1135,   L"Fuji  " ,   L"Fuji Xerox Co Ltd"},
  { 0x1136,   L"Momen." ,   L"Momentum Data Systems"},
  { 0x1137,   L"Cisco " ,   L"Cisco Systems Inc"},
  { 0x1138,   L"Ziate." ,   L"Ziatech Corporation"},
  { 0x1139,   L"Dyn. ." ,   L"Dynamic Pictures Inc"},
  { 0x113A,   L"FWB   " ,   L"FWB  Inc"},
  { 0x113B,   L"NCD   " ,   L"Network Computing Devices"},
  { 0x113C,   L"Cyclo." ,   L"Cyclone Microsystems Inc."},
  { 0x113D,   L"Leadi." ,   L"Leading Edge Products Inc"},
  { 0x113E,   L"Sanyo " ,   L"Sanyo Electric Co"},
  { 0x113F,   L"Equin." ,   L"Equinox Systems"},
  { 0x1140,   L"Inter." ,   L"Intervoice Inc"},
  { 0x1141,   L"Crest " ,   L"Crest Microsystem Inc"},
  { 0x1142,   L"Allia." ,   L"Alliance Semiconductor"},
  { 0x1143,   L"Netpo." ,   L"Netpower Inc"},
  { 0x1144,   L"Cinn.." ,   L"Cincinnati Milacron"},
  { 0x1145,   L"Workb." ,   L"Workbit Corp"},
  { 0x1146,   L"Force " ,   L"Force Computers"},
  { 0x1147,   L"Inter." ,   L"Interface Corp"},
  { 0x1148,   L"Marve." ,   L"Marvell Semiconductor Germany GmbH"},
  { 0x1149,   L"Win S." ,   L"Win System Corporation"},
  { 0x114A,   L"VMIC  " ,   L"VMIC"},
  { 0x114B,   L"Canop." ,   L"Canopus corporation"},
  { 0x114C,   L"Annab." ,   L"Annabooks"},
  { 0x114D,   L"IC Co." ,   L"IC Corporation"},
  { 0x114E,   L"Nikon " ,   L"Nikon Systems Inc"},
  { 0x114F,   L"Digi  " ,   L"Digi International"},
  { 0x1150,   L"TMC   " ,   L"Thinking Machines Corporation"},
  { 0x1151,   L"JAE   " ,   L"JAE Electronics Inc."},
  { 0x1153,   L"Land ." ,   L"Land Win Electronic Corp"},
  { 0x1154,   L"Melco " ,   L"Melco Inc"},
  { 0x1155,   L"Pine  " ,   L"Pine Technology Ltd"},
  { 0x1156,   L"Peris." ,   L"Periscope Engineering"},
  { 0x1157,   L"Avsys " ,   L"Avsys Corporation"},
  { 0x1158,   L"Voarx " ,   L"Voarx R&D Inc"},
  { 0x1159,   L"Mutech" ,   L"Mutech"},
  { 0x115A,   L"Harle." ,   L"Harlequin Ltd"},
  { 0x115B,   L"Paral." ,   L"Parallax Graphics"},
  { 0x115C,   L"Photr." ,   L"Photron Ltd."},
  { 0x115D,   L"Xircom" ,   L"Xircom"},
  { 0x115E,   L"Peer  " ,   L"Peer Protocols Inc"},
  { 0x115F,   L"Maxto." ,   L"Maxtor Corporation"},
  { 0x1160,   L"Megas." ,   L"Megasoft Inc"},
  { 0x1161,   L"PFU   " ,   L"PFU Ltd"},
  { 0x1162,   L"OA Lab" ,   L"OA Laboratory Co Ltd"},
  { 0x1163,   L"moham." ,   L"mohamed alsherif"},
  { 0x1164,   L"APT   " ,   L"Advanced Peripherals Tech"},
  { 0x1165,   L"Imagr." ,   L"Imagraph Corporation"},
  { 0x1166,   L"BRCM/." ,   L"Broadcom / ServerWorks"},
  { 0x1167,   L"Mutoh " ,   L"Mutoh Industries Inc"},
  { 0x1168,   L"Thine " ,   L"Thine Electronics Inc"},
  { 0x1169,   L"CDAC  " ,   L"Centre f/Dev. of Adv. Computing"},
  { 0x116A,   L"Lumin." ,   L"Luminex Software, Inc"},
  { 0x116B,   L"Conne." ,   L"Connectware Inc"},
  { 0x116C,   L"Int R." ,   L"Intelligent Resources"},
  { 0x116E,   L"EFI   " ,   L"Electronics for Imaging"},
  { 0x1170,   L"Inven." ,   L"Inventec Corporation"},
  { 0x1172,   L"Altera" ,   L"Altera Corporation"},
  { 0x1173,   L"Adobe " ,   L"Adobe Systems"},
  { 0x1174,   L"Bridg." ,   L"Bridgeport Machines"},
  { 0x1175,   L"Mitron" ,   L"Mitron Computer Inc."},
  { 0x1176,   L"SBE   " ,   L"SBE"},
  { 0x1177,   L"Silic." ,   L"Silicon Engineering"},
  { 0x1178,   L"Alfa  " ,   L"Alfa Inc"},
  { 0x1179,   L"Toshi." ,   L"Toshiba corporation"},
  { 0x117A,   L"A-Tre." ,   L"A-Trend Technology"},
  { 0x117B,   L"LG    " ,   L"LG (Lucky Goldstar) Electronics Inc."},
  { 0x117C,   L"Atto  " ,   L"Atto Technology"},
  { 0x117D,   L"B&D   " ,   L"Becton & Dickinson"},
  { 0x117E,   L"T/R   " ,   L"T/R Systems"},
  { 0x117F,   L"ICS   " ,   L"Integrated Circuit Systems"},
  { 0x1180,   L"Fic   " ,   L"Ricoh"},
  { 0x1183,   L"Fujik." ,   L"Fujikura Ltd"},
  { 0x1184,   L"Forks " ,   L"Forks Inc"},
  { 0x1185,   L"Dataw." ,   L"Dataworld"},
  { 0x1186,   L"D-Link" ,   L"D-Link System Inc"},
  { 0x1187,   L"Phili." ,   L"Philips Healthcare"},
  { 0x1188,   L"Shima " ,   L"Shima Seiki Manufacturing Ltd."},
  { 0x1189,   L"Matsu." ,   L"Matsushita Electronics"},
  { 0x118A,   L"Hilev." ,   L"Hilevel Technology"},
  { 0x118B,   L"Hyper." ,   L"Hypertec Pty Ltd"},
  { 0x118C,   L"Corol." ,   L"Corollary Inc"},
  { 0x118D,   L"BitFl." ,   L"BitFlow Inc"},
  { 0x118E,   L"Herms." ,   L"Hermstedt AG"},
  { 0x118F,   L"Green " ,   L"Green Logic"},
  { 0x1190,   L"Tripa." ,   L"Tripace"},
  { 0x1191,   L"Acard " ,   L"Acard Technology Corp."},
  { 0x1192,   L"Densan" ,   L"Densan Co. Ltd"},
  { 0x1194,   L"Toucan" ,   L"Toucan Technology"},
  { 0x1195,   L"Ratoc " ,   L"Ratoc System Inc"},
  { 0x1196,   L"Hytec " ,   L"Hytec Electronics Ltd"},
  { 0x1197,   L"Gage  " ,   L"Gage Applied Technologies"},
  { 0x1198,   L"Lambda" ,   L"Lambda Systems Inc"},
  { 0x1199,   L"Attac." ,   L"Attachmate Corp."},
  { 0x119A,   L"Mind ." ,   L"Mind/Share Inc."},
  { 0x119B,   L"Omega " ,   L"Omega Micro Inc."},
  { 0x119C,   L"ITI   " ,   L"Information Technology Inst."},
  { 0x119D,   L"Bug   " ,   L"Bug Sapporo Japan"},
  { 0x119E,   L"Fujit." ,   L"Fujitsu Microelectronics Ltd."},
  { 0x119F,   L"Bull  " ,   L"Bull Hn Information Systems"},
  { 0x11A1,   L"Hamam." ,   L"Hamamatsu Photonics K.K."},
  { 0x11A2,   L"Sierra" ,   L"Sierra Research and Technology"},
  { 0x11A3,   L"Deure." ,   L"Deuretzbacher GmbH & Co. Eng. KG"},
  { 0x11A4,   L"Barco " ,   L"Barco"},
  { 0x11A5,   L"Micro." ,   L"MicroUnity Systems Engineering Inc."},
  { 0x11A6,   L"Pure ." ,   L"Pure Data"},
  { 0x11A7,   L"Power." ,   L"Power Computing Corp."},
  { 0x11A8,   L"Syste." ,   L"Systech Corp."},
  { 0x11A9,   L"InnoS." ,   L"InnoSys Inc."},
  { 0x11AA,   L"Actel " ,   L"Actel"},
  { 0x11AB,   L"Marve." ,   L"Marvell Semiconductor"},
  { 0x11AC,   L"Canon " ,   L"Canon Information Systems"},
  { 0x11AD,   L"Lite-." ,   L"Lite-On Technology Corp."},
  { 0x11AE,   L"Scitex" ,   L"Scitex Corporation Ltd"},
  { 0x11AF,   L"Avid  " ,   L"Avid Technology, Inc."},
  { 0x11B0,   L"Quick." ,   L"Quicklogic Corp"},
  { 0x11B1,   L"Apric." ,   L"Apricot Computers"},
  { 0x11B2,   L"Kodak " ,   L"Eastman Kodak"},
  { 0x11B3,   L"Barr  " ,   L"Barr Systems Inc."},
  { 0x11B4,   L"Leitch" ,   L"Leitch Technology International"},
  { 0x11B5,   L"Radst." ,   L"Radstone Technology Ltd."},
  { 0x11B6,   L"Unite." ,   L"United Video Corp"},
  { 0x11B7,   L"Motor." ,   L"Motorola"},
  { 0x11B8,   L"Xpoint" ,   L"Xpoint Technologies Inc"},
  { 0x11B9,   L"Pathl." ,   L"Pathlight Technology Inc."},
  { 0x11BA,   L"Video." ,   L"Videotron Corp"},
  { 0x11BB,   L"Pyram." ,   L"Pyramid Technology"},
  { 0x11BC,   L"Net. ." ,   L"Network Peripherals Inc"},
  { 0x11BD,   L"Pinna." ,   L"Pinnacle system"},
  { 0x11BE,   L"IMI   " ,   L"International Microcircuits Inc"},
  { 0x11BF,   L"Astro." ,   L"Astrodesign Inc."},
  { 0x11C1,   L"LSI   "   ,   L"LSI Corporation"},
  { 0x11C2,   L"Sand  " ,   L"Sand Microelectronics"},
  { 0x11C4,   L"Doc.  " ,   L"Document Technologies Ind."},
  { 0x11C5,   L"Shiva " ,   L"Shiva Corporatin"},
  { 0x11C6,   L"Daini." ,   L"Dainippon Screen Mfg. Co"},
  { 0x11C7,   L"D.C.M." ,   L"D.C.M. Data Systems"},
  { 0x11C8,   L"Dolph." ,   L"Dolphin Interconnect Solutions"},
  { 0x11C9,   L"MAGMA " ,   L"MAGMA"},
  { 0x11CA,   L"LSI S." ,   L"LSI Systems Inc"},
  { 0x11CB,   L"Speci." ,   L"Specialix International Ltd."},
  { 0x11CC,   L"M&K   " ,   L"Michels & Kleberhoff Computer GmbH"},
  { 0x11CD,   L"HAL   " ,   L"HAL Computer Systems Inc."},
  { 0x11CE,   L"PRI   " ,   L"Primary Rate Inc"},
  { 0x11CF,   L"PEC   " ,   L"Pioneer Electronic Corporation"},
  { 0x11D0,   L"BAE   " ,   L"BAE SYSTEMS - Manassas"},
  { 0x11D1,   L"AuraV." ,   L"AuraVision Corporation"},
  { 0x11D2,   L"Inter." ,   L"Intercom Inc."},
  { 0x11D3,   L"Tranc." ,   L"Trancell Systems Inc"},
  { 0x11D4,   L"ADI   " ,   L"Analog Devices, Inc."},
  { 0x11D5,   L"Tahoma" ,   L"Tahoma Technology"},
  { 0x11D6,   L"Tekel." ,   L"Tekelec Technologies"},
  { 0x11D7,   L"Trent." ,   L"TRENTON Technology, Inc."},
  { 0x11D8,   L"ITD   " ,   L"Image Technologies Development"},
  { 0x11D9,   L"Tec   " ,   L"Tec Corporation"},
  { 0x11DA,   L"Novell" ,   L"Novell"},
  { 0x11DB,   L"Sega  " ,   L"Sega Enterprises Ltd"},
  { 0x11DC,   L"Quest." ,   L"Questra Corp"},
  { 0x11DD,   L"Crosf." ,   L"Crosfield Electronics Ltd"},
  { 0x11DE,   L"Zoran " ,   L"Zoran Corporation"},
  { 0x11E1,   L"Gec P." ,   L"Gec Plessey Semi Inc"},
  { 0x11E2,   L"Samsu." ,   L"Samsung Information Systems America"},
  { 0x11E3,   L"Quick." ,   L"Quicklogic Corp"},
  { 0x11E4,   L"Secon." ,   L"Second Wave Inc"},
  { 0x11E5,   L"IIX   " ,   L"IIX Consulting"},
  { 0x11E6,   L"Mitsui" ,   L"Mitsui-Zosen System Research"},
  { 0x11E8,   L"DPSI  " ,   L"Digital Processing Systems Inc"},
  { 0x11E9,   L"Highw." ,   L"Highwater Designs Ltd"},
  { 0x11EA,   L"Elsag " ,   L"Elsag Bailey"},
  { 0x11EB,   L"Forma." ,   L"Formation, Inc"},
  { 0x11EC,   L"Coreco" ,   L"Coreco Inc"},
  { 0x11ED,   L"Media." ,   L"Mediamatics"},
  { 0x11EE,   L"Dome  " ,   L"Dome Imaging Systems Inc"},
  { 0x11EF,   L"Nicol." ,   L"Nicolet Technologies BV"},
  { 0x11F0,   L"Triya." ,   L"Triya"},
  { 0x11F2,   L"Pic-T." ,   L"Picture Tel Japan KK"},
  { 0x11F3,   L"Keith." ,   L"Keithley Instruments, Inc"},
  { 0x11F4,   L"Kinet." ,   L"Kinetic Systems Corporation"},
  { 0x11F5,   L"Comp ." ,   L"Computing Devices Intl"},
  { 0x11F6,   L"Power." ,   L"Powermatic Data Systems Ltd"},
  { 0x11F7,   L"S-A   " ,   L"Scientific Atlanta"},
  { 0x11F8,   L"PMC-S." ,   L"PMC-Sierra Inc."},
  { 0x11F9,   L"I-Cube" ,   L"I-Cube Inc"},
  { 0x11FA,   L"Kasan " ,   L"Kasan Electronics Co Ltd"},
  { 0x11FB,   L"Datel " ,   L"Datel Inc"},
  { 0x11FD,   L"High ." ,   L"High Street Consultants"},
  { 0x11FE,   L"Comtr." ,   L"Comtrol Corp"},
  { 0x11FF,   L"Scion " ,   L"Scion Corp"},
  { 0x1200,   L"CSS   " ,   L"CSS Corp"},
  { 0x1201,   L"Vista " ,   L"Vista Controls Corp"},
  { 0x1202,   L"Netwo." ,   L"Network General Corp"},
  { 0x1203,   L"Agfa  " ,   L"Bayer Corporation Agfa Div"},
  { 0x1204,   L"Latti." ,   L"Lattice Semiconductor Corp"},
  { 0x1205,   L"Array " ,   L"Array Corp"},
  { 0x1206,   L"Amdahl" ,   L"Amdahl Corp"},
  { 0x1208,   L"Parsy." ,   L"Parsytec GmbH"},
  { 0x1209,   L"Sci S." ,   L"Sci Systems Inc"},
  { 0x120A,   L"Synap." ,   L"Synaptel"},
  { 0x120B,   L"Adapt." ,   L"Adaptive Solutions"},
  { 0x120D,   L"Comp ." ,   L"Compression Labs Inc."},
  { 0x120E,   L"Cycla." ,   L"Cyclades Corporation"},
  { 0x120F,   L"Essen." ,   L"Essential Communications"},
  { 0x1210,   L"Hyper." ,   L"Hyperparallel Technologies"},
  { 0x1211,   L"Brain." ,   L"Braintech Inc"},
  { 0x1213,   L"AISI  " ,   L"Applied Intelligent Systems Inc"},
  { 0x1214,   L"Perf  " ,   L"Performance Technologies Inc"},
  { 0x1215,   L"Inter." ,   L"Interware Co Ltd"},
  { 0x1216,   L"Purup." ,   L"Purup-Eskofot A/S"},
  { 0x1217,   L"O2Mic." ,   L"O2Micro Inc"},
  { 0x1218,   L"Hybri." ,   L"Hybricon Corp"},
  { 0x1219,   L"First." ,   L"First Virtual Corp"},
  { 0x121A,   L"3dfx  " ,   L"3dfx Interactive Inc"},
  { 0x121B,   L"ATM   " ,   L"Advanced Telecommunications Modules"},
  { 0x121C,   L"Nippo." ,   L"Nippon Texa Co Ltd"},
  { 0x121D,   L"LiPPE." ,   L"LiPPERT Embedded Computers GmbH"},
  { 0x121E,   L"CSPI  " ,   L"CSPI"},
  { 0x121F,   L"Arcus " ,   L"Arcus Technology Inc"},
  { 0x1220,   L"Ariel " ,   L"Ariel Corporation"},
  { 0x1221,   L"Contec" ,   L"Contec Microelectronics Europe BV"},
  { 0x1222,   L"Ancor " ,   L"Ancor Communications Inc"},
  { 0x1223,   L"Emers." ,   L"Emerson Network Power, Embedded Computing"},
  { 0x1224,   L"Int. ." ,   L"Interactive Images"},
  { 0x1225,   L"Power." ,   L"Power I/O Inc."},
  { 0x1227,   L"Tech-." ,   L"Tech-Source"},
  { 0x1228,   L"Norsk " ,   L"Norsk Elektro Optikk A/S"},
  { 0x1229,   L"Data  " ,   L"Data Kinesis Inc."},
  { 0x122A,   L"Int.  " ,   L"Integrated Telecom"},
  { 0x122B,   L"LG In." ,   L"LG Industrial Systems Co. Ltd."},
  { 0x122C,   L"sci-w." ,   L"sci-worx GmbH"},
  { 0x122D,   L"Aztech" ,   L"Aztech System Ltd"},
  { 0x122E,   L"Absol." ,   L"Absolute Analysis"},
  { 0x122F,   L"Andrew" ,   L"Andrew Corp."},
  { 0x1230,   L"Fishc." ,   L"Fishcamp Engineering"},
  { 0x1231,   L"WMI   " ,   L"Woodward McCoach Inc."},
  { 0x1233,   L"Bus-T." ,   L"Bus-Tech Inc."},
  { 0x1234,   L"Techn." ,   L"Technical Corp"},
  { 0x1236,   L"Sigma." ,   L"Sigma Designs, Inc"},
  { 0x1237,   L"Alta  " ,   L"Alta Technology Corp."},
  { 0x1238,   L"Adtran" ,   L"Adtran"},
  { 0x1239,   L"3DO   " ,   L"The 3DO Company"},
  { 0x123A,   L"Visic." ,   L"Visicom Laboratories Inc."},
  { 0x123B,   L"Seeq  " ,   L"Seeq Technology Inc."},
  { 0x123C,   L"Centu." ,   L"Century Systems Inc."},
  { 0x123D,   L"EDT   " ,   L"Engineering Design Team Inc."},
  { 0x123F,   L"C-Cube" ,   L"C-Cube Microsystems"},
  { 0x1240,   L"Marat." ,   L"Marathon Technologies Corp."},
  { 0x1241,   L"DSC   " ,   L"DSC Communications"},
  { 0x1242,   L"JNI   " ,   L"JNI Corporation"},
  { 0x1243,   L"Delph." ,   L"Delphax"},
  { 0x1244,   L"AVM   " ,   L"AVM AUDIOVISUELLES MKTG & Computer GmbH"},
  { 0x1245,   L"APD   " ,   L"APD S.A."},
  { 0x1246,   L"Dipix " ,   L"Dipix Technologies Inc"},
  { 0x1247,   L"Xylon " ,   L"Xylon Research Inc."},
  { 0x1248,   L"Centr." ,   L"Central Data Corp."},
  { 0x1249,   L"Samsu." ,   L"Samsung Electronics Co. Ltd."},
  { 0x124A,   L"AEG   " ,   L"AEG Electrocom GmbH"},
  { 0x124C,   L"Solit." ,   L"Solitron Technologies Inc."},
  { 0x124D,   L"Stall." ,   L"Stallion Technologies"},
  { 0x124E,   L"Cylink" ,   L"Cylink"},
  { 0x124F,   L"Infor." ,   L"Infortrend Technology Inc"},
  { 0x1250,   L"Hitac." ,   L"Hitachi Microcomputer System Ltd."},
  { 0x1251,   L"VLSI ." ,   L"VLSI Solution OY"},
  { 0x1253,   L"Guzik " ,   L"Guzik Technical Enterprises"},
  { 0x1254,   L"Linea." ,   L"Linear Systems Ltd."},
  { 0x1255,   L"Optib." ,   L"Optibase Ltd."},
  { 0x1256,   L"Perce." ,   L"Perceptive Solutions Inc."},
  { 0x1257,   L"Vertex" ,   L"Vertex Networks Inc."},
  { 0x1258,   L"Gilba." ,   L"Gilbarco Inc."},
  { 0x1259,   L"Allie." ,   L"Allied Telesyn International"},
  { 0x125A,   L"ABB P." ,   L"ABB Power Systems"},
  { 0x125B,   L"Asix  " ,   L"Asix Electronics Corp."},
  { 0x125C,   L"Aurora" ,   L"Aurora Technologies Inc."},
  { 0x125D,   L"ESS   " ,   L"ESS Technology"},
  { 0x125E,   L"Specv." ,   L"Specialvideo Engineering SRL"},
  { 0x125F,   L"CCT   " ,   L"Concurrent Technologies Inc."},
  { 0x1260,   L"Inter." ,   L"Intersil Corporation"},
  { 0x1261,   L"Matsu." ,   L"Matsushita-Kotobuki Electronics Indu"},
  { 0x1262,   L"ES Co." ,   L"ES Computer Co. Ltd."},
  { 0x1263,   L"Sonic." ,   L"Sonic Solutions"},
  { 0x1264,   L"Aval ." ,   L"Aval Nagasaki Corp."},
  { 0x1265,   L"Casio " ,   L"Casio Computer Co. Ltd."},
  { 0x1266,   L"Micro." ,   L"Microdyne Corp."},
  { 0x1267,   L"SA Te." ,   L"S.A. Telecommunications"},
  { 0x1268,   L"Tektr." ,   L"Tektronix"},
  { 0x1269,   L"SGS T." ,   L"Thomson-CSF/TTM"},
  { 0x126A,   L"Lexma." ,   L"Lexmark International Inc."},
  { 0x126B,   L"Adax  " ,   L"Adax Inc."},
  { 0x126C,   L"Nortel" ,   L"Nortel Networks Corp."},
  { 0x126D,   L"Splash" ,   L"Splash Technology Inc."},
  { 0x126E,   L"Sumit." ,   L"Sumitomo Metal Industries Ltd."},
  { 0x126F,   L"Sil M." ,   L"Silicon Motion"},
  { 0x1270,   L"Olymp." ,   L"Olympus Optical Co. Ltd."},
  { 0x1271,   L"GW In." ,   L"GW Instruments"},
  { 0x1272,   L"Telem." ,   L"Telematics International"},
  { 0x1273,   L"Hughes" ,   L"Hughes Network Systems"},
  { 0x1274,   L"Enson." ,   L"Ensoniq"},
  { 0x1275,   L"NetApp" ,   L"Network Appliance"},
  { 0x1276,   L"Sw Ne." ,   L"Switched Network Technologies Inc."},
  { 0x1277,   L"Comst." ,   L"Comstream"},
  { 0x1278,   L"Trans." ,   L"Transtech Parallel Systems"},
  { 0x1279,   L"Trans." ,   L"Transmeta Corp."},
  { 0x127B,   L"Pixera" ,   L"Pixera Corp"},
  { 0x127C,   L"Cross." ,   L"Crosspoint Solutions Inc."},
  { 0x127D,   L"Vela  " ,   L"Vela Research LP"},
  { 0x127E,   L"Winnow" ,   L"Winnov L.P."},
  { 0x127F,   L"Fujif." ,   L"Fujifilm"},
  { 0x1280,   L"Photo." ,   L"Photoscript Group Ltd."},
  { 0x1281,   L"Yokog." ,   L"Yokogawa Electronic Corp."},
  { 0x1282,   L"Davic." ,   L"Davicom Semiconductor Inc."},
  { 0x1283,   L" Zamo." ,   L"Waldo"},
  { 0x1285,   L"Plat ." ,   L"Platform Technologies Inc."},
  { 0x1286,   L"MAZeT " ,   L"MAZeT GmbH"},
  { 0x1287,   L"LuxSo." ,   L"LuxSonor Inc."},
  { 0x1288,   L"Times." ,   L"Timestep Corp."},
  { 0x1289,   L"AVC T." ,   L"AVC Technology Inc."},
  { 0x128A,   L"Asante" ,   L"Asante Technologies Inc."},
  { 0x128B,   L"Trans." ,   L"Transwitch Corp."},
  { 0x128C,   L"Retix " ,   L"Retix Corp."},
  { 0x128D,   L"G2 Net" ,   L"G2 Networks Inc."},
  { 0x128F,   L"Tateno" ,   L"Tateno Dennou Inc."},
  { 0x1290,   L"Sord  " ,   L"Sord Computer Corp."},
  { 0x1291,   L"NCS C." ,   L"NCS Computer Italia"},
  { 0x1292,   L"Trite." ,   L"Tritech Microelectronics Intl PTE"},
  { 0x1293,   L"M Rea." ,   L"Media Reality Technology"},
  { 0x1294,   L"Rheto." ,   L"Rhetorex Inc."},
  { 0x1295,   L"Image." ,   L"Imagenation Corp."},
  { 0x1296,   L"Kofax " ,   L"Kofax Image Products"},
  { 0x1297,   L"Shutt." ,   L"Shuttle Computer"},
  { 0x1298,   L"Spell." ,   L"Spellcaster Telecommunications Inc."},
  { 0x1299,   L"Know ." ,   L"Knowledge Technology Laboratories"},
  { 0x129A,   L"CWCEL " ,   L"Curtiss Wright Controls Electronic Systems"},
  { 0x129B,   L"Img A." ,   L"Image Access"},
  { 0x129D,   L"CompC." ,   L"CompCore Multimedia Inc."},
  { 0x129E,   L"Victo." ,   L"Victor Co. of Japan Ltd."},
  { 0x129F,   L"OEC M." ,   L"OEC Medical Systems Inc."},
  { 0x12A0,   L"A-B   " ,   L"Allen Bradley Co."},
  { 0x12A1,   L"Simpa." ,   L"Simpact Inc"},
  { 0x12A2,   L"NewGen" ,   L"NewGen Systems Corp."},
  { 0x12A3,   L"Lucent" ,   L"Lucent Technologies AMR"},
  { 0x12A4,   L"NTT E." ,   L"NTT Electronics  Corp."},
  { 0x12A5,   L"Visio." ,   L"Vision Dynamics Ltd."},
  { 0x12A6,   L"Scala." ,   L"Scalable Networks Inc."},
  { 0x12A7,   L"AMO   " ,   L"AMO GmbH"},
  { 0x12A8,   L"News ." ,   L"News Datacom"},
  { 0x12A9,   L"Xiote." ,   L"Xiotech Corp."},
  { 0x12AA,   L"SDL   " ,   L"SDL Communications Inc."},
  { 0x12AB,   L"Yuan ." ,   L"Yuan Yuan Enterprise Co. Ltd."},
  { 0x12AC,   L"Measu." ,   L"MeasureX Corp."},
  { 0x12AD,   L"MULTI." ,   L"MULTIDATA GmbH"},
  { 0x12AE,   L"Alteon" ,   L"Alteon Networks Inc."},
  { 0x12AF,   L"TDK U." ,   L"TDK USA Corp."},
  { 0x12B0,   L"Jorge." ,   L"Jorge Scientific Corp."},
  { 0x12B1,   L"Gamma." ,   L"GammaLink"},
  { 0x12B2,   L"Gen S." ,   L"General Signal Networks"},
  { 0x12B3,   L"Inter." ,   L"Interface Corp. Ltd."},
  { 0x12B4,   L"Futur." ,   L"Future Tel Inc."},
  { 0x12B5,   L"Grani." ,   L"Granite Systems Inc."},
  { 0x12B7,   L"Acumen" ,   L"Acumen"},
  { 0x12B8,   L"Korg  " ,   L"Korg"},
  { 0x12B9,   L"3Com  " ,   L"3Com Corporation"},
  { 0x12BA,   L"Bittw." ,   L"Bittware, Inc"},
  { 0x12BB,   L"Nippo." ,   L"Nippon Unisoft Corp."},
  { 0x12BC,   L"Array." ,   L"Array Microsystems"},
  { 0x12BD,   L"Compu." ,   L"Computerm Corp."},
  { 0x12BF,   L"Fujif." ,   L"Fujifilm Microdevices"},
  { 0x12C0,   L"Infim." ,   L"Infimed"},
  { 0x12C1,   L"GMM R." ,   L"GMM Research Corp."},
  { 0x12C2,   L"Mentec" ,   L"Mentec Ltd."},
  { 0x12C3,   L"Holtek" ,   L"Holtek Microelectronics Inc."},
  { 0x12C4,   L"Conne." ,   L"Connect Tech Inc."},
  { 0x12C5,   L"Pictu." ,   L"Picture Elements Inc."},
  { 0x12C6,   L"Mitani" ,   L"Mitani Corp."},
  { 0x12C7,   L"Dialo." ,   L"Dialogic Corp."},
  { 0x12C8,   L"G For." ,   L"G Force Co. Ltd."},
  { 0x12C9,   L"Gigi ." ,   L"Gigi Operations"},
  { 0x12CA,   L"ICE   " ,   L"Integrated Computing Engines, Inc."},
  { 0x12CB,   L"Antex " ,   L"Antex Electronics Corp."},
  { 0x12CC,   L"Pluto " ,   L"Pluto Technologies International"},
  { 0x12CD,   L"Aims ." ,   L"Aims Lab"},
  { 0x12CE,   L"Netsp." ,   L"Netspeed Inc."},
  { 0x12CF,   L"Proph." ,   L"Prophet Systems Inc."},
  { 0x12D0,   L"GDE S." ,   L"GDE Systems Inc."},
  { 0x12D1,   L"Huawe." ,   L"Huawei Technologies Co., Ltd."},
  { 0x12D3,   L"Vingm." ,   L"Vingmed Sound A/S"},
  { 0x12D4,   L"Ultic." ,   L"Ulticom, Inc."},
  { 0x12D5,   L"Equat." ,   L"Equator Technologies"},
  { 0x12D6,   L"Analo." ,   L"Analogic Corp."},
  { 0x12D7,   L"Biotr." ,   L"Biotronic SRL"},
  { 0x12D8,   L"Peric." ,   L"Pericom Semiconductor"},
  { 0x12D9,   L"Aculab" ,   L"Aculab Plc."},
  { 0x12DA,   L"TrueT." ,   L"TrueTime"},
  { 0x12DB,   L"Annap." ,   L"Annapolis Micro Systems Inc."},
  { 0x12DC,   L"Symic." ,   L"Symicron Computer Communication Ltd."},
  { 0x12DD,   L"MGI   " ,   L"Management Graphics Inc."},
  { 0x12DE,   L"Rainb." ,   L"Rainbow Technologies"},
  { 0x12DF,   L"SBS T." ,   L"SBS Technologies Inc."},
  { 0x12E0,   L"Chase " ,   L"Chase Research PLC"},
  { 0x12E1,   L"Ninte." ,   L"Nintendo Co. Ltd."},
  { 0x12E2,   L"Datum " ,   L"Datum Inc. Bancomm-Timing Division"},
  { 0x12E3,   L"Imati." ,   L"Imation Corp. - Medical Imaging Syst"},
  { 0x12E4,   L"Brook." ,   L"Brooktrout Technology Inc."},
  { 0x12E6,   L"Cirel " ,   L"Cirel Systems"},
  { 0x12E7,   L"Sebri." ,   L"Sebring Systems Inc"},
  { 0x12E8,   L"CRISC " ,   L"CRISC Corp."},
  { 0x12E9,   L"GE Sp." ,   L"GE Spacenet"},
  { 0x12EB,   L"Aureal" ,   L"Aureal Semiconductor"},
  { 0x12EC,   L"3A In." ,   L"3A International Inc."},
  { 0x12ED,   L"Optiv." ,   L"Optivision Inc."},
  { 0x12EE,   L"Orang." ,   L"Orange Micro, Inc."},
  { 0x12EF,   L"Vienna" ,   L"Vienna Systems"},
  { 0x12F0,   L"Pentek" ,   L"Pentek"},
  { 0x12F1,   L"Soren." ,   L"Sorenson Vision Inc."},
  { 0x12F2,   L"Gamma." ,   L"Gammagraphx Inc."},
  { 0x12F4,   L"Megat." ,   L"Megatel"},
  { 0x12F5,   L"Forks " ,   L"Forks"},
  { 0x12F7,   L"Cognex" ,   L"Cognex"},
  { 0x12F8,   L"Elect." ,   L"Electronic-Design GmbH"},
  { 0x12F9,   L"FFT   " ,   L"FourFold Technologies"},
  { 0x12FB,   L"SSP   " ,   L"Spectrum Signal Processing"},
  { 0x12FC,   L"CEC   " ,   L"Capital Equipment Corp"},
  { 0x12FE,   L"esd   " ,   L"esd Electronic System Design GmbH"},
  { 0x1303,   L"II    " ,   L"Innovative Integration"},
  { 0x1304,   L"Junip." ,   L"Juniper Networks Inc."},
  { 0x1307,   L"Compu." ,   L"ComputerBoards"},
  { 0x1308,   L"Jato  " ,   L"Jato Technologies Inc."},
  { 0x130A,   L"Mitsu." ,   L"Mitsubishi Electric Microcomputer"},
  { 0x130B,   L"Color." ,   L"Colorgraphic Communications Corp"},
  { 0x130F,   L"Advan." ,   L"Advanet Inc."},
  { 0x1310,   L"Gespac" ,   L"Gespac"},
  { 0x1312,   L"Micro." ,   L"Microscan Systems Inc"},
  { 0x1313,   L"Yaska." ,   L"Yaskawa Electric Co."},
  { 0x1316,   L"Terad." ,   L"Teradyne Inc."},
  { 0x1317,   L"ADMtek" ,   L"ADMtek Inc"},
  { 0x1318,   L"Packe." ,   L"Packet Engines, Inc."},
  { 0x1319,   L"Forte." ,   L"Forte Media"},
  { 0x131F,   L"SIIG  " ,   L"SIIG"},
  { 0x1325,   L"Salix " ,   L"Salix Technologies Inc"},
  { 0x1326,   L"Seach." ,   L"Seachange International"},
  { 0x1328,   L"CIFEL." ,   L"CIFELLI SYSTEMS CORPORATION"},
  { 0x1331,   L"RadiS." ,   L"RadiSys Corporation"},
  { 0x1332,   L"CWCEC " ,   L"Curtiss-Wright Controls Embedded Computing"},
  { 0x1335,   L"Video." ,   L"Videomail Inc."},
  { 0x133D,   L"Prisa." ,   L"Prisa Networks"},
  { 0x133F,   L"SCM   " ,   L"SCM Microsystems"},
  { 0x1342,   L"Promax" ,   L"Promax Systems Inc"},
  { 0x1344,   L"Micron" ,   L"Micron Technology, Inc."},
  { 0x1347,   L"Spect." ,   L"Spectracom Corporation"},
  { 0x134A,   L"DTC   " ,   L"DTC Technology Corp."},
  { 0x134B,   L"ARK   " ,   L"ARK Research Corp."},
  { 0x134C,   L"Chori " ,   L"Chori Joho System Co. Ltd"},
  { 0x134D,   L"PCTEL " ,   L"PCTEL Inc."},
  { 0x135A,   NULL      ,   L"Brain Boxes Limited"},
  { 0x135B,   NULL      ,   L"Giganet Inc."},
  { 0x135C,   NULL      ,   L"Quatech Inc"},
  { 0x135D,   L"ABB N." ,   L"ABB Network Partner AB"},
  { 0x135E,   L"Seale." ,   L"Sealevel Systems Inc."},
  { 0x135F,   NULL      ,   L"I-Data International A-S"},
  { 0x1360,   L"Meinb." ,   L"Meinberg Funkuhren GmbH & Co. KG"},
  { 0x1361,   NULL      ,   L"Soliton Systems K.K."},
  { 0x1363,   NULL      ,   L"Phoenix Technologies Ltd"},
  { 0x1365,   L"Hyper." ,   L"Hypercope Corp."},
  { 0x1366,   L"Teijin" ,   L"Teijin Seiki Co. Ltd."},
  { 0x1367,   NULL      ,   L"Hitachi Zosen Corporation"},
  { 0x1368,   NULL      ,   L"Skyware Corporation"},
  { 0x1369,   L"Digig." ,   L"Digigram"},
  { 0x136B,   NULL      ,   L"Kawasaki Steel Corporation"},
  { 0x136C,   NULL      ,   L"Adtek System Science Co Ltd"},
  { 0x1375,   NULL      ,   L"Boeing - Sunnyvale"},
  { 0x137A,   L"MOTU  " ,   L"Mark Of The Unicorn Inc"},
  { 0x137B,   NULL      ,   L"PPT Vision"},
  { 0x137C,   NULL      ,   L"Iwatsu Electric Co Ltd"},
  { 0x137D,   NULL      ,   L"Dynachip Corporation"},
  { 0x137E,   L"PTSC  " ,   L"Patriot Scientific Corp."},
  { 0x1380,   L"SANRI." ,   L"Sanritz Automation Co LTC"},
  { 0x1381,   NULL      ,   L"Brains Co. Ltd"},
  { 0x1382,   L"Marian" ,   L"Marian - Electronic & Software"},
  { 0x1384,   NULL      ,   L"Stellar Semiconductor Inc"},
  { 0x1385,   L"Netge." ,   L"Netgear"},
  { 0x1387,   L"CWCEL " ,   L"Curtiss-Wright Controls Electronic Systems"},
  { 0x1388,   NULL      ,   L"Hitachi Information Technology Co Ltd"},
  { 0x1389,   L"Appli." ,   L"Applicom International"},
  { 0x138A,   NULL      ,   L"Validity Sensors, Inc."},
  { 0x138B,   NULL      ,   L"Tokimec Inc"},
  { 0x138E,   NULL      ,   L"Basler GMBH"},
  { 0x138F,   NULL      ,   L"Patapsco Designs Inc"},
  { 0x1390,   L"CDI   " ,   L"Concept Development Inc."},
  { 0x1393,   NULL      ,   L"Moxa Technologies Co Ltd"},
  { 0x1394,   L"Level." ,   L"Level One Communications"},
  { 0x1395,   NULL      ,   L"Ambicom Inc"},
  { 0x1396,   NULL      ,   L"Cipher Systems Inc"},
  { 0x1397,   L"Colog." ,   L"Cologne Chip Designs GmbH"},
  { 0x1398,   NULL      ,   L"Clarion Co. Ltd"},
  { 0x139A,   NULL      ,   L"Alacritech Inc"},
  { 0x139D,   NULL      ,   L"Xstreams PLC/ EPL Limited"},
  { 0x139E,   NULL      ,   L"Echostar Data Networks"},
  { 0x13A0,   NULL      ,   L"Crystal Group Inc"},
  { 0x13A1,   NULL      ,   L"Kawasaki Heavy Industries Ltd"},
  { 0x13A3,   L"HI-FN " ,   L"HI-FN Inc."},
  { 0x13A4,   NULL      ,   L"Rascom Inc"},
  { 0x13A7,   NULL      ,   L"amc330"},
  { 0x13A8,   L"XR    " ,   L"Exar Corp."},
  { 0x13A9,   NULL      ,   L"Siemens Healthcare"},
  { 0x13AA,   NULL      ,   L"Nortel Networks - BWA Division"},
  { 0x13AF,   NULL      ,   L"T.Sqware"},
  { 0x13B1,   NULL      ,   L"Tamura Corporation"},
  { 0x13B4,   NULL      ,   L"Wellbean Co Inc"},
  { 0x13B5,   NULL      ,   L"ARM Ltd"},
  { 0x13B6,   L"DLoG  " ,   L"DLoG Gesellschaft fur elektronische Datentechnik mbH"},
  { 0x13B8,   NULL      ,   L"Nokia Telecommunications OY"},
  { 0x13BD,   L"SHARP " ,   L"Sharp Corporation"},
  { 0x13BF,   NULL      ,   L"Sharewave Inc"},
  { 0x13C0,   L"Micro." ,   L"Microgate Corp."},
  { 0x13C1,   L"3ware " ,   L"LSI"},
  { 0x13C2,   NULL      ,   L"Technotrend Systemtechnik GMBH"},
  { 0x13C3,   NULL      ,   L"Janz Computer AG"},
  { 0x13C7,   NULL      ,   L"Blue Chip Technology Ltd"},
  { 0x13CC,   NULL      ,   L"Metheus Corporation"},
  { 0x13CF,   NULL      ,   L"Studio Audio & Video Ltd"},
  { 0x13D0,   L"B2C2  " ,   L"B2C2 Inc"},
  { 0x13D1,   L"AboCom" ,   L"AboCom Systems, Inc"},
  { 0x13D4,   NULL      ,   L"Graphics Microsystems Inc"},
  { 0x13D6,   NULL      ,   L"K.I. Technology Co Ltd"},
  { 0x13D7,   L"tos62." ,   L"Toshiba Engineering Corporation"},
  { 0x13D8,   NULL      ,   L"Phobos Corporation"},
  { 0x13D9,   NULL      ,   L"Apex Inc"},
  { 0x13DC,   NULL      ,   L"Netboost Corporation"},
  { 0x13DE,   NULL      ,   L"ABB Robotics Products AB"},
  { 0x13DF,   L"E-Tech" ,   L"E-Tech Inc."},
  { 0x13E0,   L"GVC   " ,   L"GVC Corporation"},
  { 0x13E3,   NULL      ,   L"Nest Inc"},
  { 0x13E4,   NULL      ,   L"Calculex Inc"},
  { 0x13E5,   NULL      ,   L"Telesoft Design Ltd"},
  { 0x13E9,   NULL      ,   L"Intraserver Technology Inc"},
  { 0x13EA,   NULL      ,   L"Dallas Semiconductor"},
  { 0x13F0,   NULL      ,   L"IC Plus Corporation"},
  { 0x13F1,   NULL      ,   L"OCE - Industries S.A."},
  { 0x13F4,   NULL      ,   L"Troika Networks Inc"},
  { 0x13F6,   L"C-Med." ,   L"C-Media Electronics Inc."},
  { 0x13F9,   NULL      ,   L"NTT Advanced Technology Corp."},
  { 0x13FA,   L"Pentl." ,   L"Pentland Systems Ltd."},
  { 0x13FB,   NULL      ,   L"Aydin Corp"},
  { 0x13FD,   NULL      ,   L"Micro Science Inc"},
  { 0x13FE,   L"Advan." ,   L"Advantech Co., Ltd."},
  { 0x13FF,   NULL      ,   L"Silicon Spice Inc."},
  { 0x1400,   L"ArtX  " ,   L"ArtX Inc"},
  { 0x1402,   L"Meilh." ,   L"Meilhaus Electronic GmbH Germany"},
  { 0x1404,   NULL      ,   L"Fundamental Software Inc"},
  { 0x1406,   L"Oc    " ,   L"Oce Print Logics Technologies S.A."},
  { 0x1407,   L"LAVA  " ,   L"Lava Computer MFG Inc."},
  { 0x1408,   NULL      ,   L"Aloka Co. Ltd"},
  { 0x1409,   L"SUNIX " ,   L"SUNIX Co., Ltd."},
  { 0x140A,   NULL      ,   L"DSP Research Inc"},
  { 0x140B,   NULL      ,   L"Ramix Inc"},
  { 0x140D,   NULL      ,   L"Matsushita Electric Works Ltd"},
  { 0x140F,   NULL      ,   L"Salient Systems Corp"},
  { 0x1412,   L"IC En." ,   L"IC Ensemble, Inc."},
  { 0x1413,   NULL      ,   L"Addonics"},
  { 0x1415,   L"Oxford" ,   L"Oxford Semiconductor Ltd - now part of PLX Technology "},
  { 0x1418,   L"KES I." ,   L"Kyushu Electronics Systems Inc"},
  { 0x1419,   NULL      ,   L"Excel Switching Corp"},
  { 0x141B,   L"Gerd ." ,   L"Zoom Telephonics Inc"},
  { 0x141E,   NULL      ,   L"Fanuc Co. Ltd"},
  { 0x141F,   NULL      ,   L"Visiontech Ltd"},
  { 0x1420,   NULL      ,   L"Psion Dacom PLC"},
  { 0x1425,   NULL      ,   L"Chelsio Communications"},
  { 0x1428,   NULL      ,   L"Edec Co Ltd"},
  { 0x1429,   NULL      ,   L"Unex Technology Corp."},
  { 0x142A,   NULL      ,   L"Kingmax Technology Inc"},
  { 0x142B,   NULL      ,   L"Radiolan"},
  { 0x142C,   NULL      ,   L"Minton Optic Industry Co Ltd"},
  { 0x142D,   NULL      ,   L"Pixstream Inc"},
  { 0x1430,   NULL      ,   L"ITT Aerospace/Communications Division"},
  { 0x1433,   NULL      ,   L"Eltec Elektronik AG"},
  { 0x1435,   L"RTD   " ,   L"RTD Embedded Technologies, Inc."},
  { 0x1436,   NULL      ,   L"CIS Technology Inc"},
  { 0x1437,   NULL      ,   L"Nissin Inc Co"},
  { 0x1438,   NULL      ,   L"Atmel-Dream"},
  { 0x143F,   NULL      ,   L"Lightwell Co Ltd - Zax Division"},
  { 0x1441,   NULL      ,   L"Agie SA."},
  { 0x1443,   L"Unibr." ,   L"Unibrain S.A."},
  { 0x1445,   NULL      ,   L"Logical Co Ltd"},
  { 0x1446,   NULL      ,   L"Graphin Co. Ltd"},
  { 0x1447,   NULL      ,   L"Aim GMBH"},
  { 0x1448,   L"Alesis" ,   L"Alesis Studio"},
  { 0x144A,   L"ADLINK" ,   L"ADLINK Technology Inc"},
  { 0x144B,   L"Loron." ,   L"Loronix Information Systems, Inc."},
  { 0x144D,   NULL      ,   L"sanyo"},
  { 0x1450,   NULL      ,   L"Octave Communications Ind."},
  { 0x1451,   NULL      ,   L"SP3D Chip Design GMBH"},
  { 0x1453,   NULL      ,   L"Mycom Inc"},
  { 0x1458,   L"Giga-." ,   L"Giga-Byte Technologies"},
  { 0x145C,   NULL      ,   L"Cryptek"},
  { 0x145F,   L"Baldor" ,   L"Baldor Electric Company"},
  { 0x1460,   NULL      ,   L"Dynarc Inc"},
  { 0x1462,   L"MSI   " ,   L"Micro-Star International Co Ltd"},
  { 0x1463,   NULL      ,   L"Fast Corporation"},
  { 0x1464,   L"ICS   " ,   L"Interactive Circuits & Systems Ltd"},
  { 0x1468,   NULL      ,   L"Ambit Microsystems Corp."},
  { 0x1469,   NULL      ,   L"Cleveland Motion Controls"},
  { 0x146C,   NULL      ,   L"Ruby Tech Corp."},
  { 0x146D,   L"SDF   " ,   L"Tachyon Inc."},
  { 0x146E,   NULL      ,   L"WMS Gaming"},
  { 0x1471,   NULL      ,   L"Integrated Telecom Express Inc"},
  { 0x1473,   NULL      ,   L"Zapex Technologies Inc"},
  { 0x1474,   NULL      ,   L"Doug Carson & Associates"},
  { 0x1477,   NULL      ,   L"Net Insight"},
  { 0x1478,   NULL      ,   L"Diatrend Corporation"},
  { 0x147B,   NULL      ,   L"Abit Computer Corp."},
  { 0x147F,   NULL      ,   L"Nihon Unisys Ltd."},
  { 0x1482,   NULL      ,   L"Isytec - Integrierte Systemtechnik Gmbh"},
  { 0x1483,   NULL      ,   L"Labway Coporation"},
  { 0x1485,   L"Edward" ,   L"Erma - Electronic GMBH"},
  { 0x1489,   NULL      ,   L"KYE Systems Corporation"},
  { 0x148A,   NULL      ,   L"Opto 22"},
  { 0x148B,   NULL      ,   L"Innomedialogic Inc."},
  { 0x148C,   L"CP (P." ,   L"C.P. Technology Co. Ltd"},
  { 0x148D,   L"Digic." ,   L"Digicom Systems Inc."},
  { 0x148E,   NULL      ,   L"OSI Plus Corporation"},
  { 0x148F,   NULL      ,   L"Plant Equipment Inc."},
  { 0x1490,   NULL      ,   L"TC Labs Pty Ltd."},
  { 0x1491,   L"Futro." ,   L"Futronic "},
  { 0x1493,   NULL      ,   L"Maker Communications"},
  { 0x1495,   NULL      ,   L"Tokai Communications Industry Co. Ltd"},
  { 0x1496,   NULL      ,   L"Joytech Computer Co. Ltd."},
  { 0x1497,   L"SMA   " ,   L"SMA Technologie AG"},
  { 0x1498,   L"Tews  " ,   L"Tews Technologies"},
  { 0x1499,   NULL      ,   L"Micro-Technology Co Ltd"},
  { 0x149A,   L"Andor." ,   L"Andor Technology Ltd"},
  { 0x149B,   NULL      ,   L"Seiko Instruments Inc"},
  { 0x149E,   NULL      ,   L"Mapletree Networks Inc."},
  { 0x149F,   NULL      ,   L"Lectron Co Ltd"},
  { 0x14A0,   NULL      ,   L"Softing GMBH"},
  { 0x14A2,   NULL      ,   L"Millennium Engineering Inc"},
  { 0x14A4,   L"sebas." ,   L"GVC/BCM Advanced Research"},
  { 0x14A9,   L"Hiver." ,   L"Hivertec Inc."},
  { 0x14AB,   NULL      ,   L"Mentor Graphics Corp."},
  { 0x14B1,   NULL      ,   L"Nextcom K.K."},
  { 0x14B3,   L"Xpeed " ,   L"Xpeed Inc."},
  { 0x14B4,   NULL      ,   L"Philips Business Electronics B.V."},
  { 0x14B5,   L"Cream." ,   L"Creamware GmbH"},
  { 0x14B6,   NULL      ,   L"Quantum Data Corp."},
  { 0x14B7,   L"Proxim" ,   L"Proxim Inc."},
  { 0x14B9,   L"Airon." ,   L"Aironet Wireless Communication"},
  { 0x14BA,   NULL      ,   L"Internix Inc."},
  { 0x14BB,   NULL      ,   L"Semtech Corporation"},
  { 0x14BE,   NULL      ,   L"L3 Communications"},
  { 0x14C0,   L"Compal" ,   L"Compal Electronics, Inc."},
  { 0x14C1,   NULL      ,   L"Myricom Inc."},
  { 0x14C2,   NULL      ,   L"DTK Computer"},
  { 0x14C4,   NULL      ,   L"Iwasaki Information Systems Co Ltd"},
  { 0x14C5,   L"ABB   " ,   L"ABB AB (Sweden)"},
  { 0x14C6,   NULL      ,   L"Data Race Inc"},
  { 0x14C7,   L"Modte." ,   L"Modular Technology Ltd."},
  { 0x14C8,   L"Turbo." ,   L"Turbocomm Tech Inc"},
  { 0x14C9,   NULL      ,   L"Odin Telesystems Inc"},
  { 0x14CB,   NULL      ,   L"Billionton Systems Inc./Cadmus Micro Inc"},
  { 0x14CD,   L"USI   " ,   L"Universal Scientific Ind."},
  { 0x14CF,   L"Tekmi." ,   L"TEK Microsystems Inc."},
  { 0x14D4,   L"PANAC." ,   L"Panacom Technology Corporation"},
  { 0x14D5,   NULL      ,   L"Nitsuko Corporation"},
  { 0x14D6,   NULL      ,   L"Accusys Inc"},
  { 0x14D7,   NULL      ,   L"Hirakawa Hewtech Corp"},
  { 0x14D8,   NULL      ,   L"Hopf Elektronik GMBH"},
  { 0x14D9,   NULL      ,   L"Alpha Processor Inc"},
  { 0x14DB,   L"Avlab " ,   L"Avlab Technology Inc."},
  { 0x14DC,   L"Ampli." ,   L"Amplicon Liveline Limited"},
  { 0x14DD,   NULL      ,   L"Imodl Inc."},
  { 0x14DE,   NULL      ,   L"Applied Integration Corporation"},
  { 0x14E3,   NULL      ,   L"Amtelco"},
  { 0x14E4,   L"Marcio" ,   L"Broadcom"},
  { 0x14EA,   L"Planex" ,   L"Planex Communications, Inc."},
  { 0x14EB,   NULL      ,   L"Seiko Epson Corporation"},
  { 0x14EC,   NULL      ,   L"Acqiris"},
  { 0x14ED,   NULL      ,   L"Datakinetics Ltd"},
  { 0x14EF,   NULL      ,   L"Carry Computer Eng. Co Ltd"},
  { 0x14F1,   L" Cone." ,   L"Conexant  (Formerly Rockwell)"},
  { 0x14F2,   L"Mobil." ,   L"Mobility Electronics, Inc."},
  { 0x14F4,   NULL      ,   L"Tokyo Electronic Industry Co. Ltd."},
  { 0x14F5,   L"dule  " ,   L"Sopac Ltd"},
  { 0x14F6,   NULL      ,   L"Coyote Technologies LLC"},
  { 0x14F7,   NULL      ,   L"Wolf Technology Inc"},
  { 0x14F8,   NULL      ,   L"Audiocodes Inc"},
  { 0x14F9,   NULL      ,   L"AG Communications"},
  { 0x14FB,   NULL      ,   L"Transas Marine (UK) Ltd"},
  { 0x14FC,   NULL      ,   L"Quadrics Ltd"},
  { 0x14FD,   L"Silex " ,   L"Silex Technology Inc."},
  { 0x14FE,   NULL      ,   L"Archtek Telecom Corp."},
  { 0x14FF,   NULL      ,   L"Twinhead International Corp."},
  { 0x1501,   NULL      ,   L"Banksoft Canada Ltd"},
  { 0x1502,   NULL      ,   L"Mitsubishi Electric Logistics Support Co"},
  { 0x1503,   NULL      ,   L"Kawasaki LSI USA Inc"},
  { 0x1504,   NULL      ,   L"Kaiser Electronics"},
  { 0x1506,   NULL      ,   L"Chameleon Systems Inc"},
  { 0x1507,   L"Htec  " ,   L"Htec Ltd."},
  { 0x1509,   L"FIC   " ,   L"First International Computer Inc"},
  { 0x150B,   NULL      ,   L"Yamashita Systems Corp"},
  { 0x150C,   NULL      ,   L"Kyopal Co Ltd"},
  { 0x150D,   NULL      ,   L"Warpspped Inc"},
  { 0x150E,   NULL      ,   L"C-Port Corporation"},
  { 0x150F,   NULL      ,   L"Intec GMBH"},
  { 0x1510,   NULL      ,   L"Behavior Tech Computer Corp"},
  { 0x1511,   NULL      ,   L"Centillium Technology Corp"},
  { 0x1512,   L"Rosen " ,   L"Rosun Technologies Inc"},
  { 0x1513,   NULL      ,   L"Raychem"},
  { 0x1514,   NULL      ,   L"TFL LAN Inc"},
  { 0x1515,   NULL      ,   L"ICS Advent"},
  { 0x1516,   NULL      ,   L"Myson Technology Inc"},
  { 0x1517,   NULL      ,   L"Echotek Corporation"},
  { 0x1518,   NULL      ,   L"Kontron Modular Computers GmbH (PEP Modular Computers GMBH)"},
  { 0x1519,   NULL      ,   L"Telefon Aktiebolaget LM Ericsson"},
  { 0x151A,   L"Globe." ,   L"Globetek Inc."},
  { 0x151B,   L"wesam " ,   L"Combox Ltd"},
  { 0x151C,   NULL      ,   L"Digital Audio Labs Inc"},
  { 0x151D,   NULL      ,   L"Fujitsu Computer Products Of America"},
  { 0x151E,   NULL      ,   L"Matrix Corp."},
  { 0x151F,   NULL      ,   L"Topic Semiconductor Corp"},
  { 0x1520,   NULL      ,   L"Chaplet System Inc"},
  { 0x1521,   NULL      ,   L"Bell Corporation"},
  { 0x1522,   L"Mainp." ,   L"Mainpine Limited"},
  { 0x1523,   NULL      ,   L"Music Semiconductors"},
  { 0x1524,   L"mayer " ,   L"ENE Technology Inc"},
  { 0x1525,   NULL      ,   L"Impact Technologies"},
  { 0x1526,   NULL      ,   L"ISS Inc"},
  { 0x1527,   NULL      ,   L"Solectron"},
  { 0x1528,   NULL      ,   L"Acksys"},
  { 0x1529,   NULL      ,   L"American Microsystems Inc"},
  { 0x152A,   NULL      ,   L"Quickturn Design Systems"},
  { 0x152B,   NULL      ,   L"Flytech Technology Co Ltd"},
  { 0x152C,   NULL      ,   L"Macraigor Systems LLC"},
  { 0x152D,   NULL      ,   L"Quanta Computer Inc"},
  { 0x152E,   NULL      ,   L"Melec Inc"},
  { 0x152F,   NULL      ,   L"Philips - Crypto"},
  { 0x1532,   L"Razer." ,   L"Echelon Corporation"},
  { 0x1533,   NULL      ,   L"Baltimore"},
  { 0x1534,   NULL      ,   L"Road Corporation"},
  { 0x1535,   NULL      ,   L"Evergreen Technologies Inc"},
  { 0x1537,   NULL      ,   L"Datalex Communcations"},
  { 0x1538,   L"Arali." ,   L"Aralion Inc."},
  { 0x1539,   NULL      ,   L"Atelier Informatiques et Electronique Et"},
  { 0x153A,   NULL      ,   L"ONO Sokki"},
  { 0x153B,   L"cami  " ,   L"Terratec Electronic GMBH"},
  { 0x153C,   NULL      ,   L"Antal Electronic"},
  { 0x153D,   NULL      ,   L"Filanet Corporation"},
  { 0x153E,   L"Techw." ,   L"Techwell Inc"},
  { 0x153F,   L"MIPS  " ,   L"MIPS Technologies, Inc"},
  { 0x1540,   NULL      ,   L"Provideo Multimedia Co Ltd"},
  { 0x1541,   NULL      ,   L"Telocity Inc."},
  { 0x1542,   NULL      ,   L"Vivid Technology Inc"},
  { 0x1543,   NULL      ,   L"Silicon Laboratories"},
  { 0x1544,   L"DCM   " ,   L"DCM Technologies Ltd."},
  { 0x1545,   L"Visio." ,   L"VisionTek"},
  { 0x1546,   NULL      ,   L"IOI Technology Corp."},
  { 0x1547,   NULL      ,   L"Mitutoyo Corporation"},
  { 0x1548,   NULL      ,   L"Jet Propulsion Laboratory"},
  { 0x1549,   L"ISS   " ,   L"Interconnect Systems Solutions"},
  { 0x154A,   NULL      ,   L"Max Technologies Inc."},
  { 0x154B,   NULL      ,   L"Computex Co Ltd"},
  { 0x154C,   NULL      ,   L"Visual Technology Inc."},
  { 0x154D,   NULL      ,   L"PAN International Industrial Corp"},
  { 0x154E,   NULL      ,   L"Servotest Ltd"},
  { 0x154F,   NULL      ,   L"Stratabeam Technology"},
  { 0x1550,   NULL      ,   L"Open Network Co Ltd"},
  { 0x1551,   NULL      ,   L"Smart Electronic Development GMBH"},
  { 0x1553,   NULL      ,   L"Chicony Electronics Co Ltd"},
  { 0x1554,   L"PMC   " ,   L"Prolink Microsystems Corp."},
  { 0x1555,   L"Gesyt." ,   L"Gesytec GmbH"},
  { 0x1556,   NULL      ,   L"PLDA"},
  { 0x1557,   NULL      ,   L"Mediastar Co. Ltd"},
  { 0x1558,   L"dwi   " ,   L"Clevo/Kapok Computer"},
  { 0x1559,   NULL      ,   L"SI Logic Ltd"},
  { 0x155A,   NULL      ,   L"Innomedia Inc"},
  { 0x155B,   NULL      ,   L"Protac International Corp"},
  { 0x155C,   NULL      ,   L"s"},
  { 0x155D,   NULL      ,   L"MAC System Co Ltd"},
  { 0x155E,   L"KR    " ,   L"KUKA Roboter GmbH"},
  { 0x155F,   NULL      ,   L"Perle Systems Limited"},
  { 0x1560,   NULL      ,   L"Terayon Communications Systems"},
  { 0x1561,   NULL      ,   L"Viewgraphics Inc"},
  { 0x1562,   NULL      ,   L"Symbol Technologies, Inc."},
  { 0x1563,   NULL      ,   L"A-Trend Technology Co Ltd"},
  { 0x1564,   NULL      ,   L"Yamakatsu Electronics Industry Co Ltd"},
  { 0x1565,   L"xyz   " ,   L"Biostar Microtech Intl Corp"},
  { 0x1566,   NULL      ,   L"Ardent Technologies Inc"},
  { 0x1567,   NULL      ,   L"Jungsoft"},
  { 0x1568,   NULL      ,   L"DDK Electronics Inc"},
  { 0x1569,   L"Aleks." ,   L"Palit Microsystems Inc"},
  { 0x156A,   L"Avtec " ,   L"Avtec Systems Inc"},
  { 0x156B,   NULL      ,   L"S2io Inc"},
  { 0x156C,   NULL      ,   L"Vidac Electronics GMBH"},
  { 0x156D,   NULL      ,   L"Alpha-Top Corp"},
  { 0x156E,   NULL      ,   L"Alfa Inc."},
  { 0x156F,   NULL      ,   L"M-Systems Flash Disk Pioneers Ltd"},
  { 0x1570,   NULL      ,   L"Lecroy Corporation"},
  { 0x1571,   NULL      ,   L"Contemporary Controls"},
  { 0x1572,   NULL      ,   L"Otis Elevator Company"},
  { 0x1573,   NULL      ,   L"Lattice - Vantis"},
  { 0x1574,   NULL      ,   L"Fairchild Semiconductor"},
  { 0x1575,   NULL      ,   L"Voltaire Advanced Data Security Ltd"},
  { 0x1576,   L"ViewC." ,   L"Viewcast Com"},
  { 0x1578,   NULL      ,   L"Hitt"},
  { 0x1579,   NULL      ,   L"Dual Technology Corporation"},
  { 0x157A,   NULL      ,   L"Japan Elecronics Ind. Inc"},
  { 0x157B,   NULL      ,   L"Star Multimedia Corp."},
  { 0x157C,   L"Euros." ,   L"Eurosoft (UK)"},
  { 0x157D,   NULL      ,   L"Gemflex Networks"},
  { 0x157E,   NULL      ,   L"Transition Networks"},
  { 0x157F,   NULL      ,   L"PX Instruments Technology Ltd"},
  { 0x1580,   NULL      ,   L"Primex Aerospace Co."},
  { 0x1581,   NULL      ,   L"SEH Computertechnik GMBH"},
  { 0x1582,   NULL      ,   L"Cytec Corporation"},
  { 0x1583,   NULL      ,   L"Inet Technologies Inc"},
  { 0x1584,   NULL      ,   L"Uniwill Computer Corp."},
  { 0x1585,   NULL      ,   L"Marconi Commerce Systems SRL"},
  { 0x1586,   NULL      ,   L"Lancast Inc"},
  { 0x1587,   NULL      ,   L"Konica Corporation"},
  { 0x1588,   L"Solid." ,   L"Solidum Systems Corp"},
  { 0x1589,   NULL      ,   L"Atlantek Microsystems Pty Ltd"},
  { 0x158A,   NULL      ,   L"Digalog Systems Inc"},
  { 0x158B,   L"Stand." ,   L"Allied Data Technologies"},
  { 0x158C,   NULL      ,   L"Hitachi Semiconductor & Devices Sales Co"},
  { 0x158D,   NULL      ,   L"Point Multimedia Systems"},
  { 0x158E,   NULL      ,   L"Lara Technology Inc"},
  { 0x158F,   NULL      ,   L"Ditect Coop"},
  { 0x1590,   NULL      ,   L"3pardata Inc."},
  { 0x1591,   NULL      ,   L"ARN"},
  { 0x1592,   L"Syba  " ,   L"Syba Tech Ltd."},
  { 0x1593,   NULL      ,   L"Bops Inc"},
  { 0x1594,   NULL      ,   L"Netgame Ltd"},
  { 0x1595,   NULL      ,   L"Diva Systems Corp."},
  { 0x1596,   NULL      ,   L"Folsom Research Inc"},
  { 0x1597,   NULL      ,   L"Memec Design Services"},
  { 0x1598,   NULL      ,   L"Granite Microsystems"},
  { 0x1599,   NULL      ,   L"Delta Electronics Inc"},
  { 0x159A,   NULL      ,   L"General Instrument"},
  { 0x159B,   NULL      ,   L"Faraday Technology Corp"},
  { 0x159C,   NULL      ,   L"Stratus Computer Systems"},
  { 0x159D,   NULL      ,   L"Ningbo Harrison Electronics Co Ltd"},
  { 0x159E,   NULL      ,   L"A-Max Technology Co Ltd"},
  { 0x159F,   NULL      ,   L"Galea Network Security"},
  { 0x15A0,   NULL      ,   L"Compumaster SRL"},
  { 0x15A1,   NULL      ,   L"Geocast Network Systems Inc"},
  { 0x15A2,   NULL      ,   L"Catalyst Enterprises Inc"},
  { 0x15A3,   NULL      ,   L"Italtel"},
  { 0x15A4,   L"Rafa  " ,   L"X-Net OY"},
  { 0x15A5,   NULL      ,   L"Toyota MACS Inc"},
  { 0x15A6,   NULL      ,   L"Sunlight Ultrasound Technologies Ltd"},
  { 0x15A7,   NULL      ,   L"SSE Telecom Inc"},
  { 0x15A8,   NULL      ,   L"Shanghai Communications Technologies Cen"},
  { 0x15AA,   NULL      ,   L"Moreton Bay"},
  { 0x15AB,   NULL      ,   L"Bluesteel Networks Inc"},
  { 0x15AC,   NULL      ,   L"North Atlantic Instruments"},
  { 0x15AD,   L"VMware" ,   L"VMware Inc."},
  { 0x15AE,   NULL      ,   L"Amersham Pharmacia Biotech"},
  { 0x15B0,   NULL      ,   L"Zoltrix International Limited"},
  { 0x15B1,   NULL      ,   L"Source Technology Inc"},
  { 0x15B2,   NULL      ,   L"Mosaid Technologies Inc."},
  { 0x15B3,   NULL      ,   L"Mellanox Technology"},
  { 0x15B4,   NULL      ,   L"CCI/Triad"},
  { 0x15B5,   NULL      ,   L"Cimetrics Inc"},
  { 0x15B6,   NULL      ,   L"Texas Memory Systems Inc"},
  { 0x15B7,   NULL      ,   L"Sandisk Corp."},
  { 0x15B8,   NULL      ,   L"Addi-Data GMBH"},
  { 0x15B9,   NULL      ,   L"Maestro Digital Communications"},
  { 0x15BA,   NULL      ,   L"Impacct Technology Corp"},
  { 0x15BB,   NULL      ,   L"Portwell Inc"},
  { 0x15BC,   L"Agile." ,   L"Agilent Technologies"},
  { 0x15BD,   NULL      ,   L"DFI Inc."},
  { 0x15BE,   NULL      ,   L"Sola Electronics"},
  { 0x15BF,   NULL      ,   L"High Tech Computer Corp (HTC)"},
  { 0x15C0,   L"BVM   " ,   L"BVM Limited"},
  { 0x15C1,   NULL      ,   L"Quantel"},
  { 0x15C2,   NULL      ,   L"Newer Technology Inc"},
  { 0x15C3,   NULL      ,   L"Taiwan Mycomp Co Ltd"},
  { 0x15C4,   NULL      ,   L"EVSX Inc"},
  { 0x15C5,   NULL      ,   L"Procomp Informatics Ltd"},
  { 0x15C6,   NULL      ,   L"Technical University Of Budapest"},
  { 0x15C7,   NULL      ,   L"Tateyama System Laboratory Co Ltd"},
  { 0x15C8,   NULL      ,   L"Penta Media Co. Ltd"},
  { 0x15C9,   NULL      ,   L"Serome Technology Inc"},
  { 0x15CA,   NULL      ,   L"Bitboys OY"},
  { 0x15CB,   NULL      ,   L"AG Electronics Ltd"},
  { 0x15CC,   NULL      ,   L"Hotrail Inc."},
  { 0x15CD,   NULL      ,   L"Dreamtech Co Ltd"},
  { 0x15CE,   NULL      ,   L"Genrad Inc."},
  { 0x15CF,   NULL      ,   L"Hilscher GMBH"},
  { 0x15D1,   L"Infin." ,   L"Infineon Technologies AG"},
  { 0x15D2,   NULL      ,   L"FIC (First International Computer Inc)"},
  { 0x15D3,   NULL      ,   L"NDS Technologies Israel Ltd"},
  { 0x15D4,   NULL      ,   L"Iwill Corporation"},
  { 0x15D5,   NULL      ,   L"Tatung Co."},
  { 0x15D6,   NULL      ,   L"Entridia Corporation"},
  { 0x15D7,   NULL      ,   L"Rockwell-Collins Inc"},
  { 0x15D8,   NULL      ,   L"Cybernetics Technology Co Ltd"},
  { 0x15D9,   L"uttank" ,   L"Super Micro Computer Inc"},
  { 0x15DA,   NULL      ,   L"Cyberfirm Inc."},
  { 0x15DB,   NULL      ,   L"Applied Computing Systems Inc."},
  { 0x15DC,   L"Litro." ,   L"Litronic Inc."},
  { 0x15DD,   NULL      ,   L"Sigmatel Inc."},
  { 0x15DE,   NULL      ,   L"Malleable Technologies Inc"},
  { 0x15E0,   NULL      ,   L"Cacheflow Inc"},
  { 0x15E1,   L"VTG   " ,   L"Voice Technologies Group"},
  { 0x15E2,   NULL      ,   L"Quicknet Technologies Inc"},
  { 0x15E3,   NULL      ,   L"Networth Technologies Inc"},
  { 0x15E4,   NULL      ,   L"VSN Systemen BV"},
  { 0x15E5,   NULL      ,   L"Valley Technologies Inc"},
  { 0x15E6,   NULL      ,   L"Agere Inc."},
  { 0x15E7,   NULL      ,   L"GET Engineering Corp."},
  { 0x15E8,   L"akmal " ,   L"National Datacomm Corp."},
  { 0x15E9,   NULL      ,   L"Pacific Digital Corp."},
  { 0x15EA,   NULL      ,   L"Tokyo Denshi Sekei K.K."},
  { 0x15EB,   NULL      ,   L"Drsearch GMBH"},
  { 0x15EC,   NULL      ,   L"Beckhoff Automation GmbH"},
  { 0x15ED,   NULL      ,   L"Macrolink Inc"},
  { 0x15EE,   NULL      ,   L"IN Win Development Inc."},
  { 0x15EF,   NULL      ,   L"Intelligent Paradigm Inc"},
  { 0x15F0,   NULL      ,   L"B-Tree Systems Inc"},
  { 0x15F1,   NULL      ,   L"Times N Systems Inc"},
  { 0x15F2,   L"SPOT ." ,   L"SPOT Imaging Solutions a division of Diagnostic Instruments, Inc"},
  { 0x15F3,   NULL      ,   L"Digitmedia Corp."},
  { 0x15F4,   NULL      ,   L"Valuesoft"},
  { 0x15F5,   NULL      ,   L"Power Micro Research"},
  { 0x15F6,   NULL      ,   L"Extreme Packet Device Inc"},
  { 0x15F7,   NULL      ,   L"Banctec"},
  { 0x15F8,   NULL      ,   L"Koga Electronics Co"},
  { 0x15F9,   NULL      ,   L"Zenith Electronics Co"},
  { 0x15FA,   L"Axzam " ,   L"Axzam Corporation"},
  { 0x15FB,   NULL      ,   L"Zilog Inc."},
  { 0x15FC,   NULL      ,   L"Techsan Electronics Co Ltd"},
  { 0x15FD,   NULL      ,   L"N-Cubed.Net"},
  { 0x15FE,   NULL      ,   L"Kinpo Electronics Inc"},
  { 0x15FF,   NULL      ,   L"Fastpoint Technologies Inc."},
  { 0x1600,   NULL      ,   L"Northrop Grumman - Canada Ltd"},
  { 0x1601,   NULL      ,   L"Tenta Technology"},
  { 0x1602,   NULL      ,   L"Prosys-TEC Inc."},
  { 0x1603,   NULL      ,   L"Nokia Wireless Business Communications"},
  { 0x1604,   NULL      ,   L"Central System Research Co Ltd"},
  { 0x1605,   NULL      ,   L"Pairgain Technologies"},
  { 0x1606,   NULL      ,   L"Europop AG"},
  { 0x1607,   NULL      ,   L"Lava Semiconductor Manufacturing Inc."},
  { 0x1608,   L"nuri  " ,   L"Automated Wagering International"},
  { 0x1609,   NULL      ,   L"Sciemetric Instruments Inc"},
  { 0x160A,   NULL      ,   L"Kollmorgen Servotronix"},
  { 0x160B,   NULL      ,   L"Onkyo Corp."},
  { 0x160C,   NULL      ,   L"Oregon Micro Systems Inc."},
  { 0x160D,   NULL      ,   L"Aaeon Electronics Inc"},
  { 0x160E,   NULL      ,   L"CML Emergency Services"},
  { 0x160F,   NULL      ,   L"ITEC Co Ltd"},
  { 0x1610,   NULL      ,   L"Tottori Sanyo Electric Co Ltd"},
  { 0x1611,   NULL      ,   L"Bel Fuse Inc."},
  { 0x1612,   NULL      ,   L"Telesynergy Research Inc."},
  { 0x1613,   NULL      ,   L"System Craft Inc."},
  { 0x1614,   NULL      ,   L"Jace Tech Inc."},
  { 0x1615,   NULL      ,   L"Equus Computer Systems Inc"},
  { 0x1616,   NULL      ,   L"Iotech Inc."},
  { 0x1617,   NULL      ,   L"Rapidstream Inc"},
  { 0x1618,   NULL      ,   L"Esec SA"},
  { 0x1619,   L"FarSi." ,   L"FarSite Communications Limited"},
  { 0x161B,   NULL      ,   L"Mobilian Israel Ltd"},
  { 0x161C,   NULL      ,   L"Berkshire Products"},
  { 0x161D,   NULL      ,   L"Gatec"},
  { 0x161E,   NULL      ,   L"Kyoei Sangyo Co Ltd"},
  { 0x161F,   L"Arima " ,   L"Arima Computer Corporation"},
  { 0x1620,   NULL      ,   L"Sigmacom Co Ltd"},
  { 0x1621,   NULL      ,   L"Lynx Studio Technology Inc"},
  { 0x1622,   L"NHC   " ,   L"Nokia Home Communications"},
  { 0x1623,   NULL      ,   L"KRF Tech Ltd"},
  { 0x1624,   NULL      ,   L"CE Infosys GMBH"},
  { 0x1625,   NULL      ,   L"Warp Nine Engineering"},
  { 0x1626,   NULL      ,   L"TDK Semiconductor Corp."},
  { 0x1627,   NULL      ,   L"BCom Electronics Inc"},
  { 0x1629,   NULL      ,   L"Kongsberg Spacetec a.s."},
  { 0x162A,   NULL      ,   L"Sejin Computerland Co Ltd"},
  { 0x162B,   NULL      ,   L"Shanghai Bell Company Limited"},
  { 0x162C,   NULL      ,   L"C&H Technologies Inc"},
  { 0x162D,   NULL      ,   L"Reprosoft Co Ltd"},
  { 0x162E,   NULL      ,   L"Margi Systems Inc"},
  { 0x162F,   NULL      ,   L"Rohde & Schwarz GMBH & Co KG"},
  { 0x1630,   NULL      ,   L"Sky Computers Inc"},
  { 0x1631,   NULL      ,   L"NEC Computer International"},
  { 0x1632,   NULL      ,   L"Verisys Inc"},
  { 0x1633,   NULL      ,   L"Adac Corporation"},
  { 0x1634,   NULL      ,   L"Visionglobal Network Corp."},
  { 0x1635,   NULL      ,   L"Decros / S.ICZ a.s."},
  { 0x1636,   NULL      ,   L"Jean Company Ltd"},
  { 0x1637,   NULL      ,   L"NSI"},
  { 0x1638,   L" Eumi." ,   L"Eumitcom Technology Inc"},
  { 0x163A,   NULL      ,   L"Air Prime Inc"},
  { 0x163B,   NULL      ,   L"Glotrex Co Ltd"},
  { 0x163C,   NULL      ,   L"intel"},
  { 0x163D,   NULL      ,   L"Heidelberg Digital LLC"},
  { 0x163E,   L"&#107." ,   L"3dpower"},
  { 0x163F,   NULL      ,   L"Renishaw PLC"},
  { 0x1640,   NULL      ,   L"Intelliworxx Inc"},
  { 0x1641,   NULL      ,   L"MKNet Corporation"},
  { 0x1642,   NULL      ,   L"Bitland"},
  { 0x1643,   NULL      ,   L"Hajime Industries Ltd"},
  { 0x1644,   NULL      ,   L"Western Avionics Ltd"},
  { 0x1645,   NULL      ,   L"Quick-Serv. Computer Co. Ltd"},
  { 0x1646,   NULL      ,   L"Nippon Systemware Co Ltd"},
  { 0x1647,   NULL      ,   L"Hertz Systemtechnik GMBH"},
  { 0x1648,   NULL      ,   L"MeltDown Systems LLC"},
  { 0x1649,   NULL      ,   L"Jupiter Systems"},
  { 0x164A,   NULL      ,   L"Aiwa Co. Ltd"},
  { 0x164C,   NULL      ,   L"Department Of Defense"},
  { 0x164D,   NULL      ,   L"Ishoni Networks"},
  { 0x164E,   NULL      ,   L"Micrel Inc."},
  { 0x164F,   L"DataV." ,   L"Datavoice (Pty) Ltd."},
  { 0x1650,   NULL      ,   L"Admore Technology Inc."},
  { 0x1651,   NULL      ,   L"Chaparral Network Storage"},
  { 0x1652,   NULL      ,   L"Spectrum Digital Inc."},
  { 0x1653,   L"Natur." ,   L"Nature Worldwide Technology Corp"},
  { 0x1654,   NULL      ,   L"Sonicwall Inc"},
  { 0x1655,   NULL      ,   L"Dazzle Multimedia Inc."},
  { 0x1656,   NULL      ,   L"Insyde Software Corp"},
  { 0x1657,   NULL      ,   L"Brocade Communications Systems"},
  { 0x1658,   L"Med A." ,   L"Med Associates Inc."},
  { 0x1659,   NULL      ,   L"Shiba Denshi Systems Inc."},
  { 0x165A,   NULL      ,   L"Epix Inc."},
  { 0x165B,   NULL      ,   L"Real-Time Digital Inc."},
  { 0x165C,   NULL      ,   L"Kondo Kagaku"},
  { 0x165D,   L"Salva " ,   L"Hsing Tech. Enterprise Co. Ltd."},
  { 0x165E,   NULL      ,   L"Hyunju Computer Co. Ltd."},
  { 0x165F,   L"Comart" ,   L"Comartsystem Korea"},
  { 0x1660,   L"NETSEC" ,   L"Network Security Technologies Inc. (NetSec)"},
  { 0x1661,   NULL      ,   L"Worldspace Corp."},
  { 0x1662,   NULL      ,   L"Int Labs"},
  { 0x1663,   NULL      ,   L"Elmec Inc. Ltd."},
  { 0x1664,   NULL      ,   L"Fastfame Technology Co. Ltd."},
  { 0x1665,   NULL      ,   L"Edax Inc."},
  { 0x1666,   NULL      ,   L"Norpak Corporation"},
  { 0x1667,   NULL      ,   L"CoSystems Inc."},
  { 0x1668,   L"Actio." ,   L"Actiontec Electronics Inc."},
  { 0x166A,   NULL      ,   L"Komatsu Ltd."},
  { 0x166B,   NULL      ,   L"Supernet Inc."},
  { 0x166C,   NULL      ,   L"Shade Ltd."},
  { 0x166D,   NULL      ,   L"Sibyte Inc."},
  { 0x166E,   NULL      ,   L"Schneider Automation Inc."},
  { 0x166F,   NULL      ,   L"Televox Software Inc."},
  { 0x1670,   NULL      ,   L"Rearden Steel"},
  { 0x1671,   NULL      ,   L"Atan Technology Inc."},
  { 0x1672,   NULL      ,   L"Unitec Co. Ltd."},
  { 0x1673,   NULL      ,   L"pctel"},
  { 0x1675,   NULL      ,   L"Square Wave Technology"},
  { 0x1676,   L"Gatew." ,   L"Emachines Inc."},
  { 0x1677,   NULL      ,   L"Bernecker + Rainer"},
  { 0x1678,   NULL      ,   L"INH Semiconductor"},
  { 0x1679,   NULL      ,   L"Tokyo Electron Device Ltd."},
  { 0x167F,   L"iba   " ,   L"iba AG"},
  { 0x1680,   L"Dunti " ,   L"Dunti Corp."},
  { 0x1681,   L"Hercu." ,   L"Hercules"},
  { 0x1682,   L"PINE  " ,   L"PINE Technology, Ltd."},
  { 0x1688,   L"Castl." ,   L"CastleNet Technology Inc."},
  { 0x168A,   L"USA   " ,   L"Utimaco Safeware AG"},
  { 0x168B,   NULL      ,   L"Circut Assembly Corp."},
  { 0x168C,   L"Ather." ,   L"Atheros Communications Inc."},
  { 0x168D,   L"NMI   " ,   L"NMI Electronics Ltd."},
  { 0x168E,   L"Hyund." ,   L"Hyundai MultiCAV Computer Co. Ltd."},
  { 0x168F,   L"Gsb   " ,   L"KDS Innotech Corp."},
  { 0x1690,   L"NetCo." ,   L"NetContinuum, Inc."},
  { 0x1693,   L"FERMA " ,   L"FERMA"},
  { 0x1695,   L"EPoX  " ,   L"EPoX Computer Co., Ltd."},
  { 0x16AE,   L"SFNT  " ,   L"SafeNet Inc."},
  { 0x16B3,   NULL      ,   L"CNF Mobile Solutions"},
  { 0x16B8,   L"Sonne." ,   L"Sonnet Technologies, Inc."},
  { 0x16CA,   L"Cenat." ,   L"Cenatek Inc."},
  { 0x16CB,   L"Minol." ,   L"Minolta Co. Ltd."},
  { 0x16CC,   L"Inari " ,   L"Inari Inc."},
  { 0x16D0,   NULL      ,   L"Systemax"},
  { 0x16E0,   L"3MTS  " ,   L"Third Millenium Test Solutions, Inc."},
  { 0x16E5,   NULL      ,   L"Intellon Corporation"},
  { 0x16EC,   L"USR   " ,   L"U.S. Robotics"},
  { 0x16F0,   NULL      ,   L"LaserLinc Inc."},
  { 0x16F1,   L"Adicti" ,   L"Adicti Corp."},
  { 0x16F3,   L"Jetway" ,   L"Jetway Information Co., Ltd"},
  { 0x16F6,   L"Video." ,   L"VideoTele.com Inc."},
  { 0x1700,   L"Antara" ,   L"Antara LLC"},
  { 0x1701,   NULL      ,   L"Interactive Computer Products Inc."},
  { 0x1702,   L"IMC   " ,   L"Internet Machines Corp."},
  { 0x1703,   L"Desana" ,   L"Desana Systems"},
  { 0x1704,   L"Clear." ,   L"Clearwater Networks"},
  { 0x1705,   L"Digit." ,   L"Digital First"},
  { 0x1706,   L"PBC   " ,   L"Pacific Broadband Communications"},
  { 0x1707,   L"Cogen." ,   L"Cogency Semiconductor Inc."},
  { 0x1708,   L"Harris" ,   L"Harris Corp."},
  { 0x1709,   L"Zarli." ,   L"Zarlink Semiconductor"},
  { 0x170A,   L"Alpine" ,   L"Alpine Electronics Inc."},
  { 0x170B,   L"NetOc." ,   L"NetOctave Inc."},
  { 0x170C,   L"Yotta." ,   L"YottaYotta Inc."},
  { 0x170D,   L"SMI   " ,   L"SensoMotoric Instruments GmbH"},
  { 0x170E,   L"San V." ,   L"San Valley Systems, Inc."},
  { 0x170F,   L"Cyber." ,   L"Cyberdyne Inc."},
  { 0x1710,   L"Pelago" ,   L"Pelago Nutworks"},
  { 0x1711,   L"NetSc." ,   L"MyName Technologies, Inc."},
  { 0x1712,   L"NICE  " ,   L"NICE Systems Inc."},
  { 0x1713,   L"TOPCON" ,   L"TOPCON Corp."},
  { 0x1725,   L"Vites." ,   L"Vitesse Semiconductor"},
  { 0x1734,   L"Fujit." ,   L"Fujitsu-Siemens Computers GmbH"},
  { 0x1737,   L"LinkS." ,   L"LinkSys"},
  { 0x173B,   L"Altima" ,   L"Altima Communications Inc."},
  { 0x1743,   L"Peppe." ,   L"Peppercon AG"},
  { 0x174B,   L"PC Pa." ,   L"PC Partner Limited"},
  { 0x1752,   L"AMW E." ,   L"Global Brands Manufacture Ltd."},
  { 0x1753,   L"TeraR." ,   L"TeraRecon, Inc."},
  { 0x1755,   L"Alche." ,   L"Alchemy Semiconductor Inc."},
  { 0x176A,   L"GDC   " ,   L"General Dynamics Canada"},
  { 0x1775,   NULL      ,   L"General Electric"},
  { 0x1789,   L"Ennyah" ,   L"Ennyah Technologies Corp"},
  { 0x1793,   L"Unite." ,   L"Unitech Electronics Co., Ltd"},
  { 0x17A1,   L"Tasco." ,   L"Tascorp"},
  { 0x17A7,   L"Start." ,   L"Start Network Technology Co., Ltd."},
  { 0x17AA,   L"lenovo" ,   L"Legend Ltd. (Beijing)"},
  { 0x17AB,   L"Phili." ,   L"Phillips Components"},
  { 0x17AF,   L"Hight." ,   L"Hightech Information Systems, Ltd."},
  { 0x17BE,   L"Phili." ,   L"Philips Semiconductors"},
  { 0x17C0,   L"Wistr." ,   L"Wistron Corp."},
  { 0x17C4,   NULL      ,   L"Movita"},
  { 0x17CC,   L"NetCh." ,   L"NetChip"},
  { 0x17cd,   L"Caden." ,   L"Cadence Design Systems"},
  { 0x17D5,   L"Neter." ,   L"Neterion Inc."},
  { 0x17db,   L"Cray. " ,   L"Cray, Inc."},
  { 0x17E9,   NULL      ,   L"DH electronics GmbH / Sabrent"},
  { 0x17EE,   L"Conne." ,   L"Connect Components, Ltd."},
  { 0x17F3,   L"RDC   " ,   L"RDC Semiconductor Co., Ltd."},
  { 0x17FE,   L"INPRO." ,   L"INPROCOMM"},
  { 0x1813,   L"Ambie." ,   L"Ambient Technologies Inc"},
  { 0x1814,   L"Ralin." ,   L"Ralink Technology, Corp."},
  { 0x1815,   L"devolo" ,   L"devolo AG"},
  { 0x1820,   L"Infin." ,   L"InfiniCon Systems, Inc."},
  { 0x1824,   L"Avoce." ,   L"Avocent"},
  { 0x1841,   L"D-lin." ,   L"Panda Platinum"},
  { 0x1860,   L"Prima." ,   L"Primagraphics Ltd."},
  { 0x186C,   L"Humus." ,   L"Humusoft S.R.O"},
  { 0x1887,   L"Elan  " ,   L"Elan Digital Systems Ltd"},
  { 0x1888,   NULL      ,   L"Varisys Limited"},
  { 0x188D,   L"Millo." ,   L"Millogic Ltd."},
  { 0x1890,   NULL      ,   L"Egenera, Inc."},
  { 0x18BC,   NULL      ,   L"Info-Tek Corp."},
  { 0x18C9,   L"ARVOO " ,   L"ARVOO Engineering BV"},
  { 0x18CA,   L"XGI   " ,   L"XGI Technology Inc"},
  { 0x18F1,   L"Spc   " ,   L"Spectrum Systementwicklung Microelectronic GmbH"},
  { 0x18F4,   L"Napat." ,   L"Napatech A/S"},
  { 0x18F7,   L"Commt." ,   L"Commtech, Inc."},
  { 0x18FB,   NULL      ,   L"Resilience Corporation"},
  { 0x1904,   L"Ritmo " ,   L"Ritmo"},
  { 0x1905,   L"WIS C." ,   L"WIS Technology, Inc."},
  { 0x1910,   L"Seawa." ,   L"Seaway Networks"},
  { 0x1912,   L"USB   " ,   L"usb 3.0 Renesas Electronics"},
  { 0x1931,   NULL      ,   L"Option NV"},
  { 0x1941,   L"Stelar" ,   L"Stelar"},
  { 0x1954,   NULL      ,   L"One Stop Systems, Inc."},
  { 0x1969,   L"ATHR  " ,   L"Atheros Communications"},
  { 0x1971,   L"dreser" ,   L"AGEIA Technologies, Inc."},
  { 0x197B,   L"santo." ,   L"JMicron Technology Corp."},
  { 0x198a,   L"Nalla." ,   L"Nallatech"},
  { 0x1991,   L"Tps   " ,   L"Topstar Digital Technologies Co., Ltd."},
  { 0x19a2,   L"Emul. " ,   L"ServerEngines"},
  { 0x19A8,   L"DAQDA." ,   L"DAQDATA GmbH"},
  { 0x19AC,   L"Kaste." ,   L"Kasten Chase Applied Research"},
  { 0x19B6,   L"Mikro." ,   L"Mikrotik"},
  { 0x19E2,   L"Vector" ,   L"Vector Informatik GmbH"},
  { 0x19E3,   L"DDRdr." ,   L"DDRdrive LLC"},
  { 0x1A08,   NULL      ,   L"Linux Networx"},
  { 0x1a41,   L"Tilera" ,   L"Tilera Corporation"},
  { 0x1A42,   NULL      ,   L"Imaginant"},
  { 0x1B13,   L"Jaton." ,   L"Jaton Corporation USA"},
  { 0x1B21,   L"Asust." ,   L"Asustek - ASMedia Technology Inc."},
  { 0x1B6F,   L"Etron " ,   L"Etron"},
  { 0x1B73,   L"Fresc." ,   L"Fresco Logic Inc."},
  { 0x1B91,   NULL      ,   L"Averna"},
  { 0x1BAD,   L"ReFLEX" ,   L"ReFLEX CES"},
  { 0x1C0F,   L"Monar." ,   L"Monarch Innovative Technologies Pvt Ltd's "},
  { 0x1C32,   L"Highl." ,   L"Highland Technology, Inc."},
  { 0x1c39,   L"TH-VN " ,   L"Thomson Video Networks"},
  { 0x1DE1,   L"Tekram" ,   L"Tekram"},
  { 0x1FCF,   L"Miran." ,   L"Miranda Technologies Ltd."},
  { 0x2001,   NULL      ,   L"Temporal Research Ltd"},
  { 0x2646,   L"Kings." ,   L"Kingston Technology Co."},
  { 0x270F,   L"Chain." ,   L"ChainTek Computer Co. Ltd."},
  { 0x2EC1,   NULL      ,   L"Zenic Inc"},
  { 0x3388,   L"Hint  " ,   L"Hint Corp."},
  { 0x3411,   NULL      ,   L"Quantum Designs (H.K.) Inc."},
  { 0x3513,   L"ARCOM " ,   L"ARCOM Control Systems Ltd."},
  { 0x38EF,   NULL      ,   L"4links"},
  { 0x3D3D,   L"3DLabs" ,   L"3Dlabs, Inc. Ltd"},
  { 0x4005,   L"Avance" ,   L"Avance Logic Inc."},
  { 0x4144,   L"Alpha." ,   L"Alpha Data"},
  { 0x416C,   NULL      ,   L"Aladdin Knowledge Systems"},
  { 0x4348,   L"Nanji." ,   L"wch.cn"},
  { 0x4680,   L"UMAX ." ,   L"UMAX Computer Corp."},
  { 0x4843,   L"Hercu." ,   L"Hercules Computer Technology"},
  { 0x4943,   NULL      ,   L"Growth Networks"},
  { 0x4954,   L"Integ." ,   L"Integral Technologies"},
  { 0x4978,   L"Axil  " ,   L"Axil Computer Inc."},
  { 0x4C48,   L"Lung ." ,   L"Lung Hwa Electronics"},
  { 0x4C53,   L"SBS   " ,   L"SBS-OR Industrial Computers"},
  { 0x4CA1,   NULL      ,   L"Seanix Technology Inc"},
  { 0x4D51,   L"Mediaq" ,   L"Mediaq Inc."},
  { 0x4D54,   NULL      ,   L"Microtechnica Co Ltd"},
  { 0x4DDC,   L"ILC   " ,   L"ILC Data Device Corp."},
  { 0x04E8,   L" sams." ,   L"Samsung Windows Portable Devices"},
  { 0x5053,   L"TBS/V." ,   L"TBS/Voyetra Technologies"},
  { 0x508A,   L"Samsu." ,   L"Samsung T10 MP3 Player"},
  { 0x5136,   NULL      ,   L"S S Technologies"},
  { 0x5143,   L"Qualc." ,   L"Qualcomm Inc. USA"},
  { 0x5333,   L"S3G   " ,   L"S3 Graphics Co., Ltd"},
  { 0x544C,   NULL      ,   L"Teralogic Inc"},
  { 0x5555,   L"Genro." ,   L"Genroco Inc."},
  { 0x5853,   L" Citr." ,   L"Citrix Systems, Inc."},
  { 0x6409,   NULL      ,   L"Logitec Corp."},
  { 0x6666,   L"Decis." ,   L"Decision Computer International Co."},
  { 0x6945,   L"ASMed." ,   L"ASMedia Technology Inc."},
  { 0x7604,   L"O.N.  " ,   L"O.N. Electric Co. Ltd."},
  { 0x07d1,   L"D-Link" ,   L"D-Link Corporation"},
  { 0x8080,   L"Xirli." ,   L"Xirlink, Inc"},
  { 0x8086,   L"Intel " ,   L"Intel Corporation"},
  { 0x8087,   L"Intel " ,   L"Intel"},
  { 0x80EE,   L"Virtu." ,   L"Oracle Corporation - InnoTek Systemberatung GmbH"},
  { 0x8866,   L"T-Squ." ,   L"T-Square Design Inc."},
  { 0x8888,   L"Sil M." ,   L"Silicon Magic"},
  { 0x8E0E,   L"Compu." ,   L"Computone Corporation"},
  { 0x9004,   L"Adapt." ,   L"Adaptec Inc"},
  { 0x9005,   L"Adapt." ,   L"Adaptec Inc"},
  { 0x919A,   NULL      ,   L"Gigapixel Corp"},
  { 0x9412,   L"Holtek" ,   L"Holtek"},
  { 0x9699,   NULL      ,   L"Omni Media Technology Inc."},
  { 0x9710,   L"MosCh." ,   L"MosChip Semiconductor Technology"},
  { 0x9902,   L"StarG." ,   L"StarGen, Inc."},
  { 0xA0A0,   L"Aopen " ,   L"Aopen Inc."},
  { 0xA0F1,   NULL      ,   L"Unisys Corporation"},
  { 0xA200,   L"NEC   " ,   L"NEC Corp."},
  { 0xA259,   L"HP    " ,   L"Hewlett Packard"},
  { 0xA304,   L"Sony  " ,   L"Sony"},
  { 0xA727,   NULL      ,   L"3com Corporation"},
  { 0xAA42,   L"Scitex" ,   L"Scitex Digital Video"},
  { 0xAC1E,   NULL      ,   L"Digital Receiver Technology Inc"},
  { 0xB1B3,   L"Shiva " ,   L"Shiva Europe Ltd."},
  { 0xB894,   NULL      ,   L"Brown & Sharpe Mfg. Co."},
  { 0xBEEF,   L"Minds." ,   L"Mindstream Computing"},
  { 0xC001,   L"TSI   " ,   L"TSI Telsys"},
  { 0xC0A9,   L"Micro." ,   L"Micron/Crucial Technology"},
  { 0xC0DE,   NULL      ,   L"Motorola"},
  { 0xC0FE,   L"Mot E." ,   L"Motion Engineering Inc."},
  { 0xC622,   NULL      ,   L"Hudson Soft Co Ltd"},
  { 0xCA50,   L"Varian" ,   L"Varian, Inc"},
  { 0xCAFE,   NULL      ,   L"Chrysalis-ITS"},
  { 0xCCCC,   NULL      ,   L"Catapult Communications"},
  { 0xD4D4,   L"Proce." ,   L"Curtiss-Wright Controls Embedded Computing"},
  { 0xDC93,   NULL      ,   L"Dawicontrol"},
  { 0xDEAD,   L"Indig." ,   L"Indigita Corporation"},
  { 0xDEAF,   NULL      ,   L"Middle Digital, Inc"},
  { 0xE159,   L"Tiger." ,   L"Tiger Jet Network Inc"},
  { 0xE4BF,   NULL      ,   L"EKF Elektronik GMBH"},
  { 0xEA01,   NULL      ,   L"Eagle Technology"},
  { 0xEABB,   L"Aashi." ,   L"Aashima Technology B.V."},
  { 0xEACE,   L"Endace" ,   L"Endace Measurement Systems Ltd."},
  { 0xECC0,   L"Echo  " ,   L"Echo Digital Audio Corporation"},
  { 0xEDD8,   L"ARK L." ,   L"ARK Logic, Inc"},
  { 0xF5F5,   NULL      ,   L"F5 Networks Inc."},
  { 0xFA57,   L"Inter." ,   L"Interagon AS"},
  { 0xFFFF,   NULL      ,   NULL},
} ;

/**
  With giving Vendor ID, this function will return a short vendor name of the Vendor ID.
  
  @param[in]  VendorId       - Vendor ID for the PCI device.
  @param[out] **ShortString  - Vendor name for the Vendor ID.
  
  @retval EFI_SUCCESS   - Find the vendor name.
  @retval EFI_NOT_FOUND - Can not find the vendor name.
  
**/
EFI_STATUS
GetVerdorIdShortName (
  IN UINT16  VendorId,
  OUT CHAR16 **ShortString
  )
{
  UINT16      Index = 0;

  *ShortString = NULL;

  while(TRUE) {
    if (mPciVenTable[Index].VendorId == 0xFFFF) {
      break;
    } else if (mPciVenTable[Index].VendorId == VendorId) {
      *ShortString = mPciVenTable[Index].ShortName;
      return EFI_SUCCESS;
    }
    Index++;
  }
  
  return EFI_NOT_FOUND;
}

/**
  With giving Vendor ID, this function will return a long vendor name of the Vendor ID.
  
  @param[in]  VendorId       - Vendor ID for the PCI device.
  @param[out] **LongString   - Vendor name for the Vendor ID.
  
  @retval EFI_SUCCESS   - Find the vendor name.
  @retval EFI_NOT_FOUND - Can not find the vendor name.
  
**/
EFI_STATUS
GetVerdorIdLongName (
  IN UINT16  VendorId,
  OUT CHAR16 **LongString
  )
{
  UINT16      Index = 0;

  *LongString = NULL;

  while(TRUE) {
    if (mPciVenTable[Index].VendorId == 0xFFFF) {
      break;
    } else if (mPciVenTable[Index].VendorId == VendorId) {
      *LongString = mPciVenTable[Index].LongName;
      return EFI_SUCCESS;
    }
    Index++;
  }
  
  return EFI_NOT_FOUND;
}

